import { Question } from "@/types/question";

export const careerInterestQuestions: Question[] = [
  // STAGE 1: Core Interests & Exploratory Affinities (Questions 1–5)
  {
    id: "car_q1",
    title: "When starting a major project, which part of the work naturally energizes you the most?",
    subtitle: "Innate motivation and early task preference.",
    type: "single-choice",
    dimension: "Analytical",
    options: [
      { id: "car_1_a", label: "Digging into raw data, researching benchmarks, and analyzing underlying metrics.", value: 5 },
      { id: "car_1_b", label: "Brainstorming completely novel visual themes, copy, or concept models.", value: 3 },
      { id: "car_1_c", label: "Mapping out milestones, logistics, and organizing task dependencies.", value: 3 },
      { id: "car_1_d", label: "Gathering stakeholders together and aligning everyone around a shared vision.", value: 3 },
    ],
  },
  {
    id: "car_q2",
    title: "I am energized by unstructured creative problems where there is no standard formula or right answer.",
    subtitle: "Divergent thinking and creative tolerance.",
    type: "likert-scale",
    dimension: "Creative",
    options: [
      { id: "car_2_1", label: "Strongly Disagree", value: 1 },
      { id: "car_2_2", label: "Disagree", value: 2 },
      { id: "car_2_3", label: "Neutral", value: 3 },
      { id: "car_2_4", label: "Agree", value: 4 },
      { id: "car_2_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "car_q3",
    title: "I naturally step up to guide group direction, make tough trade-offs, and represent the team externally.",
    subtitle: "Leadership and ownership orientation.",
    type: "likert-scale",
    dimension: "Leadership",
    options: [
      { id: "car_3_1", label: "Strongly Disagree", value: 1 },
      { id: "car_3_2", label: "Disagree", value: 2 },
      { id: "car_3_3", label: "Neutral", value: 3 },
      { id: "car_3_4", label: "Agree", value: 4 },
      { id: "car_3_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "car_q4",
    title: "I derive immense satisfaction from building flawless workflows, documentation, and operational systems.",
    subtitle: "Systematic execution and operational precision.",
    type: "likert-scale",
    dimension: "Operational",
    options: [
      { id: "car_4_1", label: "Strongly Disagree", value: 1 },
      { id: "car_4_2", label: "Disagree", value: 2 },
      { id: "car_4_3", label: "Neutral", value: 3 },
      { id: "car_4_4", label: "Agree", value: 4 },
      { id: "car_4_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "car_q5",
    title: "A career only feels deeply fulfilling to me if it directly relieves suffering, teaches, or improves human lives.",
    subtitle: "Service and prosocial mission orientation.",
    type: "likert-scale",
    dimension: "Service",
    options: [
      { id: "car_5_1", label: "Strongly Disagree", value: 1 },
      { id: "car_5_2", label: "Disagree", value: 2 },
      { id: "car_5_3", label: "Neutral", value: 3 },
      { id: "car_5_4", label: "Agree", value: 4 },
      { id: "car_5_5", label: "Strongly Agree", value: 5 },
    ],
  },

  // STAGE 2: Deep Work & Daily Task Flow (Questions 6–10)
  {
    id: "car_q6",
    title: "How often do you find yourself building spreadsheets, writing code, or evaluating statistical patterns for fun?",
    subtitle: "Analytical deep focus frequency.",
    type: "frequency",
    dimension: "Analytical",
    options: [
      { id: "car_6_a", label: "Rarely or never", value: 1 },
      { id: "car_6_b", label: "Occasionally when needed", value: 2 },
      { id: "car_6_c", label: "Frequently every week", value: 4 },
      { id: "car_6_d", label: "Constantly — it is my default thinking mode", value: 5 },
    ],
  },
  {
    id: "car_q7",
    title: "Designing visual layouts, drafting compelling narratives, or generating original artistic concepts excites me.",
    subtitle: "Creative synthesis appetite.",
    type: "likert-scale",
    dimension: "Creative",
    options: [
      { id: "car_7_1", label: "Strongly Disagree", value: 1 },
      { id: "car_7_2", label: "Disagree", value: 2 },
      { id: "car_7_3", label: "Neutral", value: 3 },
      { id: "car_7_4", label: "Agree", value: 4 },
      { id: "car_7_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "car_q8",
    title: "I enjoy pitching bold strategic visions, convincing skeptical stakeholders, and negotiating high-stakes agreements.",
    subtitle: "Strategic persuasion and executive drive.",
    type: "likert-scale",
    dimension: "Leadership",
    options: [
      { id: "car_8_1", label: "Strongly Disagree", value: 1 },
      { id: "car_8_2", label: "Disagree", value: 2 },
      { id: "car_8_3", label: "Neutral", value: 3 },
      { id: "car_8_4", label: "Agree", value: 4 },
      { id: "car_8_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "car_q9",
    title: "I excel at taking chaotic, disorganized initiatives and turning them into repeatable, predictable processes.",
    subtitle: "Operational structure transformation.",
    type: "likert-scale",
    dimension: "Operational",
    options: [
      { id: "car_9_1", label: "Strongly Disagree", value: 1 },
      { id: "car_9_2", label: "Disagree", value: 2 },
      { id: "car_9_3", label: "Neutral", value: 3 },
      { id: "car_9_4", label: "Agree", value: 4 },
      { id: "car_9_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "car_q10",
    title: "I am energized when coaching an individual through personal obstacles, mentoring junior peers, or helping clients thrive.",
    subtitle: "One-on-one empathic empowerment.",
    type: "likert-scale",
    dimension: "Service",
    options: [
      { id: "car_10_1", label: "Strongly Disagree", value: 1 },
      { id: "car_10_2", label: "Disagree", value: 2 },
      { id: "car_10_3", label: "Neutral", value: 3 },
      { id: "car_10_4", label: "Agree", value: 4 },
      { id: "car_10_5", label: "Strongly Agree", value: 5 },
    ],
  },

  // STAGE 3: Situational Choices & Workplace Trade-Offs (Questions 11–15)
  {
    id: "car_q11",
    title: "If offered your choice of four high-impact corporate roles, which responsibility would you choose?",
    subtitle: "Situational career domain preference.",
    type: "scenario",
    dimension: "Analytical",
    options: [
      { id: "car_11_a", label: "Head of Research & Data Science: Unraveling complex predictive models.", value: 5 },
      { id: "car_11_b", label: "Chief Brand Creative Director: Shaping visual aesthetics and brand stories.", value: 3 },
      { id: "car_11_c", label: "Chief Operating Officer: Perfecting execution timelines and supply chains.", value: 3 },
      { id: "car_11_d", label: "People & Community Officer: Championing wellbeing and user advocacy.", value: 2 },
    ],
  },
  {
    id: "car_q12",
    title: "In a team brainstorming session, I would rather propose 10 radical experimental ideas than evaluate existing ones.",
    subtitle: "Divergent ideation appetite.",
    type: "likert-scale",
    dimension: "Creative",
    options: [
      { id: "car_12_1", label: "Strongly Disagree", value: 1 },
      { id: "car_12_2", label: "Disagree", value: 2 },
      { id: "car_12_3", label: "Neutral", value: 3 },
      { id: "car_12_4", label: "Agree", value: 4 },
      { id: "car_12_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "car_q13",
    title: "When an ambiguous crisis strikes, I feel confident taking command and issuing clear priorities to others.",
    subtitle: "Crisis decision-making leadership.",
    type: "likert-scale",
    dimension: "Leadership",
    options: [
      { id: "car_13_1", label: "Strongly Disagree", value: 1 },
      { id: "car_13_2", label: "Disagree", value: 2 },
      { id: "car_13_3", label: "Neutral", value: 3 },
      { id: "car_13_4", label: "Agree", value: 4 },
      { id: "car_13_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "car_q14",
    title: "I find sloppy execution, missed project details, and poor organizational hygiene frustrating.",
    subtitle: "High operational standards.",
    type: "likert-scale",
    dimension: "Operational",
    options: [
      { id: "car_14_1", label: "Strongly Disagree", value: 1 },
      { id: "car_14_2", label: "Disagree", value: 2 },
      { id: "car_14_3", label: "Neutral", value: 3 },
      { id: "car_14_4", label: "Agree", value: 4 },
      { id: "car_14_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "car_q15",
    title: "I would gladly accept lower financial compensation if my day-to-day role directly lifted disadvantaged communities.",
    subtitle: "Mission-over-compensation trade-off.",
    type: "likert-scale",
    dimension: "Service",
    options: [
      { id: "car_15_1", label: "Strongly Disagree", value: 1 },
      { id: "car_15_2", label: "Disagree", value: 2 },
      { id: "car_15_3", label: "Neutral", value: 3 },
      { id: "car_15_4", label: "Agree", value: 4 },
      { id: "car_15_5", label: "Strongly Agree", value: 5 },
    ],
  },

  // STAGE 4: Long-Term Legacy & Ideal Work Environment (Questions 16–20)
  {
    id: "car_q16",
    title: "When reading articles or professional books, I gravitate toward technical whitepapers, case studies, and quantitative breakdowns.",
    subtitle: "Intellectual analytical appetite.",
    type: "likert-scale",
    dimension: "Analytical",
    options: [
      { id: "car_16_1", label: "Strongly Disagree", value: 1 },
      { id: "car_16_2", label: "Disagree", value: 2 },
      { id: "car_16_3", label: "Neutral", value: 3 },
      { id: "car_16_4", label: "Agree", value: 4 },
      { id: "car_16_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "car_q17",
    title: "I need regular freedom to experiment, iterate, and author original creative work without rigid bureaucratic oversight.",
    subtitle: "Creative autonomy requirement.",
    type: "likert-scale",
    dimension: "Creative",
    options: [
      { id: "car_17_1", label: "Strongly Disagree", value: 1 },
      { id: "car_17_2", label: "Disagree", value: 2 },
      { id: "car_17_3", label: "Neutral", value: 3 },
      { id: "car_17_4", label: "Agree", value: 4 },
      { id: "car_17_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "car_q18",
    title: "My ideal long-term legacy is having built and scaled an organization that achieves lasting market influence.",
    subtitle: "Executive builder ambition.",
    type: "likert-scale",
    dimension: "Leadership",
    options: [
      { id: "car_18_1", label: "Strongly Disagree", value: 1 },
      { id: "car_18_2", label: "Disagree", value: 2 },
      { id: "car_18_3", label: "Neutral", value: 3 },
      { id: "car_18_4", label: "Agree", value: 4 },
      { id: "car_18_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "car_q19",
    title: "I prefer working in environments with well-defined protocols, clear accountability, and rock-solid dependability.",
    subtitle: "Operational dependability fit.",
    type: "likert-scale",
    dimension: "Operational",
    options: [
      { id: "car_19_1", label: "Strongly Disagree", value: 1 },
      { id: "car_19_2", label: "Disagree", value: 2 },
      { id: "car_19_3", label: "Neutral", value: 3 },
      { id: "car_19_4", label: "Agree", value: 4 },
      { id: "car_19_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "car_q20",
    title: "The moments in my professional journey that brought the most profound joy were when someone I helped expressed genuine gratitude.",
    subtitle: "Service impact resonance.",
    type: "likert-scale",
    dimension: "Service",
    options: [
      { id: "car_20_1", label: "Strongly Disagree", value: 1 },
      { id: "car_20_2", label: "Disagree", value: 2 },
      { id: "car_20_3", label: "Neutral", value: 3 },
      { id: "car_20_4", label: "Agree", value: 4 },
      { id: "car_20_5", label: "Strongly Agree", value: 5 },
    ],
  },
];
