import { Question } from "@/types/question";

export const sleepQuestions: Question[] = [
  // STAGE 1: Circadian Consistency & Timing (Questions 1–5)
  {
    id: "slp_q1",
    title: "How consistent is your morning wake-up time between weekdays and weekends?",
    subtitle: "Circadian rhythm anchoring through light and wake timing.",
    type: "single-choice",
    dimension: "Circadian Consistency",
    options: [
      { id: "slp_1_a", label: "Virtually identical (within 30 minutes every day)", value: 5, description: "Highly anchored circadian rhythm" },
      { id: "slp_1_b", label: "Slight difference (within 1 hour on weekends)", value: 4, description: "Solid baseline regularity" },
      { id: "slp_1_c", label: "Moderate shift (1 to 2 hours difference)", value: 2, description: "Mild social jetlag" },
      { id: "slp_1_d", label: "Large shift (sleeping in 2.5+ hours on weekends)", value: 1, description: "Severe circadian disruption" },
    ],
  },
  {
    id: "slp_q2",
    title: "I go to bed at roughly the same hour every night without prolonged delays.",
    subtitle: "Bedtime predictability and habitual rhythm.",
    type: "likert-scale",
    dimension: "Circadian Consistency",
    options: [
      { id: "slp_2_1", label: "Strongly Disagree", value: 1 },
      { id: "slp_2_2", label: "Disagree", value: 2 },
      { id: "slp_2_3", label: "Neutral", value: 3 },
      { id: "slp_2_4", label: "Agree", value: 4 },
      { id: "slp_2_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "slp_q3",
    title: "How soon after waking do you expose your eyes to outdoor sunlight or bright daylight?",
    subtitle: "Primary zeitgeber for resetting the suprachiasmatic nucleus.",
    type: "single-choice",
    dimension: "Circadian Consistency",
    options: [
      { id: "slp_3_a", label: "Within 20–30 minutes of waking", value: 5 },
      { id: "slp_3_b", label: "Within the first 1–2 hours", value: 3 },
      { id: "slp_3_c", label: "Around midday or afternoon only", value: 2 },
      { id: "slp_3_d", label: "I remain in dim indoor lighting for most of the day", value: 1 },
    ],
  },
  {
    id: "slp_q4",
    title: "My daily meal times (breakfast, dinner) follow a predictable schedule.",
    subtitle: "Peripheral circadian clocks in metabolic organs.",
    type: "likert-scale",
    dimension: "Circadian Consistency",
    options: [
      { id: "slp_4_1", label: "Strongly Disagree", value: 1 },
      { id: "slp_4_2", label: "Disagree", value: 2 },
      { id: "slp_4_3", label: "Neutral", value: 3 },
      { id: "slp_4_4", label: "Agree", value: 4 },
      { id: "slp_4_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "slp_q5",
    title: "Scenario: It is a Friday evening after a demanding week. How do you approach your sleep timing?",
    subtitle: "Select the behavior that reflects your typical weekend transition.",
    type: "scenario",
    dimension: "Circadian Consistency",
    options: [
      { id: "slp_5_a", label: "I relax and head to bed near my usual hour, preserving my natural wake rhythm.", value: 5, description: "Circadian preservation" },
      { id: "slp_5_b", label: "I stay up 1 hour later for a movie, but avoid drastic schedule shifts.", value: 4, description: "Moderate flexibility" },
      { id: "slp_5_c", label: "I stay awake past 2 AM bingeing media and sleep until midday Saturday.", value: 1, description: "Circadian dislocation" },
      { id: "slp_5_d", label: "I have no set pattern; weekends are unpredictable and erratic.", value: 1, description: "Absence of circadian structure" },
    ],
  },

  // STAGE 2: Evening Wind-Down & Sleep Environment (Questions 6–10)
  {
    id: "slp_q6",
    title: "How many minutes before sleep do you completely disconnect from interactive screens (phones, computers)?",
    subtitle: "Melatonin suppression and cognitive pre-sleep arousal.",
    type: "single-choice",
    dimension: "Evening Wind-Down",
    options: [
      { id: "slp_6_a", label: "60+ minutes before bed", value: 5 },
      { id: "slp_6_b", label: "30–60 minutes before bed", value: 4 },
      { id: "slp_6_c", label: "10–20 minutes before bed", value: 2 },
      { id: "slp_6_d", label: "I scroll in bed right until my eyes close", value: 1 },
    ],
  },
  {
    id: "slp_q7",
    title: "My bedroom environment is cool (roughly 65–68°F / 18–20°C), dark, and quiet.",
    subtitle: "Thermoregulation and sensory sleep cues.",
    type: "likert-scale",
    dimension: "Evening Wind-Down",
    options: [
      { id: "slp_7_1", label: "Strongly Disagree", value: 1 },
      { id: "slp_7_2", label: "Disagree", value: 2 },
      { id: "slp_7_3", label: "Neutral", value: 3 },
      { id: "slp_7_4", label: "Agree", value: 4 },
      { id: "slp_7_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "slp_q8",
    title: "How frequently do you consume caffeine within 8 hours of bedtime?",
    subtitle: "Adenosine receptor antagonism and slow-wave sleep reduction.",
    type: "frequency",
    dimension: "Evening Wind-Down",
    reversed: true,
    options: [
      { id: "slp_8_a", label: "Never — my cutoff is early afternoon", value: 1 },
      { id: "slp_8_b", label: "Occasionally once a week", value: 2 },
      { id: "slp_8_c", label: "Frequently (3–4 days a week)", value: 3 },
      { id: "slp_8_d", label: "Daily into the late afternoon or evening", value: 4 },
    ],
  },
  {
    id: "slp_q9",
    title: "I have an intentional, calming pre-sleep routine (e.g., warm shower, reading physical books, light stretching).",
    subtitle: "Parasympathetic transition cues.",
    type: "likert-scale",
    dimension: "Evening Wind-Down",
    options: [
      { id: "slp_9_1", label: "Strongly Disagree", value: 1 },
      { id: "slp_9_2", label: "Disagree", value: 2 },
      { id: "slp_9_3", label: "Neutral", value: 3 },
      { id: "slp_9_4", label: "Agree", value: 4 },
      { id: "slp_9_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "slp_q10",
    title: "How often do you eat heavy meals or sugary snacks within 2 hours of going to sleep?",
    subtitle: "Digestive activation and core body temperature elevation.",
    type: "frequency",
    dimension: "Evening Wind-Down",
    reversed: true,
    options: [
      { id: "slp_10_a", label: "Rarely or never", value: 1 },
      { id: "slp_10_b", label: "Once or twice a week", value: 2 },
      { id: "slp_10_c", label: "Most nights", value: 3 },
      { id: "slp_10_d", label: "Every night right before bed", value: 4 },
    ],
  },

  // STAGE 3: Sleep Quality & Nighttime Continuity (Questions 11–15)
  {
    id: "slp_q11",
    title: "On a typical night, approximately how many minutes does it take you to fall asleep once your lights are off?",
    subtitle: "Sleep onset latency indicator.",
    type: "single-choice",
    dimension: "Sleep Quality",
    options: [
      { id: "slp_11_a", label: "10 to 20 minutes (optimal latency)", value: 5 },
      { id: "slp_11_b", label: "Under 5 minutes (often indicates severe sleep debt)", value: 3 },
      { id: "slp_11_c", label: "25 to 45 minutes", value: 2 },
      { id: "slp_11_d", label: "Over 45 minutes of restless tossing", value: 1 },
    ],
  },
  {
    id: "slp_q12",
    title: "How frequently do you wake up in the middle of the night and struggle to return to sleep?",
    subtitle: "Sleep fragmentation and maintenance insomnia cues.",
    type: "frequency",
    dimension: "Sleep Quality",
    reversed: true,
    options: [
      { id: "slp_12_a", label: "Rarely or never", value: 1 },
      { id: "slp_12_b", label: "Once or twice a week, but fall back asleep quickly", value: 2 },
      { id: "slp_12_c", label: "3 to 4 nights a week with prolonged awakenings", value: 3 },
      { id: "slp_12_d", label: "Almost every night with extensive wakefulness", value: 4 },
    ],
  },
  {
    id: "slp_q13",
    title: "I achieve roughly 7 to 9 hours of total sleep per night on average.",
    subtitle: "Recommended adult sleep duration sufficiency.",
    type: "likert-scale",
    dimension: "Sleep Quality",
    options: [
      { id: "slp_13_1", label: "Strongly Disagree (under 5.5 hours)", value: 1 },
      { id: "slp_13_2", label: "Disagree (5.5–6.5 hours)", value: 2 },
      { id: "slp_13_3", label: "Neutral (roughly 6.5–7 hours)", value: 3 },
      { id: "slp_13_4", label: "Agree (7–8.5 hours)", value: 4 },
      { id: "slp_13_5", label: "Strongly Agree (7.5–9 hours consistently)", value: 5 },
    ],
  },
  {
    id: "slp_q14",
    title: "Scenario: You wake up at 3:30 AM with your mind active about an upcoming project. What do you do?",
    subtitle: "CBT-I conditioned arousal management.",
    type: "scenario",
    dimension: "Sleep Quality",
    options: [
      { id: "slp_14_a", label: "I practice deep slow breathing in the dark and drift back to sleep.", value: 5, description: "Calm somatic self-soothing" },
      { id: "slp_14_b", label: "If awake after 20 minutes, I move to dim light, read, and return when sleepy.", value: 5, description: "Clinical stimulus control adherence" },
      { id: "slp_14_c", label: "I pick up my smartphone to browse social media or check email.", value: 1, description: "Circadian and dopamine re-activation" },
      { id: "slp_14_d", label: "I toss and turn with mounting anxiety about being exhausted tomorrow.", value: 1, description: "Catastrophic sleep rumination" },
    ],
  },
  {
    id: "slp_q15",
    title: "My sleep feels deep, uninterrupted, and physically restorative.",
    subtitle: "Subjective sleep quality index.",
    type: "likert-scale",
    dimension: "Sleep Quality",
    options: [
      { id: "slp_15_1", label: "Strongly Disagree", value: 1 },
      { id: "slp_15_2", label: "Disagree", value: 2 },
      { id: "slp_15_3", label: "Neutral", value: 3 },
      { id: "slp_15_4", label: "Agree", value: 4 },
      { id: "slp_15_5", label: "Strongly Agree", value: 5 },
    ],
  },

  // STAGE 4: Morning Alertness & Daytime Energy (Questions 16–20)
  {
    id: "slp_q16",
    title: "Within 30 minutes of waking, how alert and energized do you generally feel?",
    subtitle: "Sleep inertia dissipation efficiency.",
    type: "single-choice",
    dimension: "Morning Alertness",
    options: [
      { id: "slp_16_a", label: "Clear-headed, refreshed, and ready to start the day", value: 5 },
      { id: "slp_16_b", label: "Mild grogginess that clears within 15–20 minutes", value: 4 },
      { id: "slp_16_c", label: "Heavy fog requiring multiple cups of caffeine to function", value: 2 },
      { id: "slp_16_d", label: "Exhausted and wishing I could sleep for another 4 hours", value: 1 },
    ],
  },
  {
    id: "slp_q17",
    title: "I can comfortably sustain mental focus through the early afternoon without experiencing a severe energy crash.",
    subtitle: "Postprandial dip resilience and sleep debt indicator.",
    type: "likert-scale",
    dimension: "Morning Alertness",
    options: [
      { id: "slp_17_1", label: "Strongly Disagree", value: 1 },
      { id: "slp_17_2", label: "Disagree", value: 2 },
      { id: "slp_17_3", label: "Neutral", value: 3 },
      { id: "slp_17_4", label: "Agree", value: 4 },
      { id: "slp_17_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "slp_q18",
    title: "How frequently do you feel an overwhelming urge to nap or doze off during passive daytime activities (reading, watching video, riding transit)?",
    subtitle: "Epworth sleepiness daytime scale proxy.",
    type: "frequency",
    dimension: "Morning Alertness",
    reversed: true,
    options: [
      { id: "slp_18_a", label: "Never or rarely", value: 1 },
      { id: "slp_18_b", label: "Occasionally if I slept poorly the night before", value: 2 },
      { id: "slp_18_c", label: "Several days every week", value: 3 },
      { id: "slp_18_d", label: "Almost every single afternoon", value: 4 },
    ],
  },
  {
    id: "slp_q19",
    title: "I rarely rely on stimulant drinks or energy pills just to maintain basic cognitive clarity.",
    subtitle: "Exogenous chemical wakefulness dependency.",
    type: "likert-scale",
    dimension: "Morning Alertness",
    options: [
      { id: "slp_19_1", label: "Strongly Disagree", value: 1 },
      { id: "slp_19_2", label: "Disagree", value: 2 },
      { id: "slp_19_3", label: "Neutral", value: 3 },
      { id: "slp_19_4", label: "Agree", value: 4 },
      { id: "slp_19_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "slp_q20",
    title: "Overall, how satisfied are you with your restorative sleep habits and daytime vitality?",
    subtitle: "Holistic self-perceived rest satisfaction.",
    type: "single-choice",
    dimension: "Morning Alertness",
    options: [
      { id: "slp_20_a", label: "Highly satisfied — I wake up restored and operate with steady energy", value: 5 },
      { id: "slp_20_b", label: "Generally satisfied with minor room for routine optimization", value: 4 },
      { id: "slp_20_c", label: "Somewhat unsatisfied — I frequently feel unrefreshed", value: 2 },
      { id: "slp_20_d", label: "Very unsatisfied — chronic exhaustion impacts my quality of life", value: 1 },
    ],
  },
];
