import { Question } from "@/types/question";

export const digitalWellbeingQuestions: Question[] = [
  // STAGE 1: Notification Resilience & Reactive Reflexes (Questions 1–5)
  {
    id: "dwb_q1",
    title: "When your phone vibrates or chimes with a non-urgent alert, how quickly do you check it?",
    subtitle: "Dopamine-driven conditioned response latency.",
    type: "single-choice",
    dimension: "Notification Resilience",
    reversed: true, // Immediate check = lower score
    options: [
      { id: "dwb_1_a", label: "I leave it unread and check only during scheduled breaks", value: 1 },
      { id: "dwb_1_b", label: "Within 10–15 minutes once I finish my current task", value: 2 },
      { id: "dwb_1_c", label: "Within 1–2 minutes; curiosity pulls my attention", value: 3 },
      { id: "dwb_1_d", label: "Instantaneously, often interrupting in-person conversations or work", value: 4 },
    ],
  },
  {
    id: "dwb_q2",
    title: "I have disabled non-essential app notifications (social media, games, news alerts) on my devices.",
    subtitle: "Proactive environmental design for attention defense.",
    type: "likert-scale",
    dimension: "Notification Resilience",
    options: [
      { id: "dwb_2_1", label: "Strongly Disagree", value: 1 },
      { id: "dwb_2_2", label: "Disagree", value: 2 },
      { id: "dwb_2_3", label: "Neutral", value: 3 },
      { id: "dwb_2_4", label: "Agree", value: 4 },
      { id: "dwb_2_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "dwb_q3",
    title: "How frequently do you experience phantom vibration syndrome (falsely feeling your phone buzz in your pocket)?",
    subtitle: "Neurological sensory hyper-vigilance to device alerts.",
    type: "frequency",
    dimension: "Notification Resilience",
    reversed: true,
    options: [
      { id: "dwb_3_a", label: "Never or rarely", value: 1 },
      { id: "dwb_3_b", label: "Once or twice a month", value: 2 },
      { id: "dwb_3_c", label: "Several times a week", value: 3 },
      { id: "dwb_3_d", label: "Multiple times daily", value: 4 },
    ],
  },
  {
    id: "dwb_q4",
    title: "I can comfortably leave my phone in another room for 3+ hours without anxiety or compulsive checking.",
    subtitle: "Separation tolerance and device dependency.",
    type: "likert-scale",
    dimension: "Notification Resilience",
    options: [
      { id: "dwb_4_1", label: "Strongly Disagree", value: 1 },
      { id: "dwb_4_2", label: "Disagree", value: 2 },
      { id: "dwb_4_3", label: "Neutral", value: 3 },
      { id: "dwb_4_4", label: "Agree", value: 4 },
      { id: "dwb_4_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "dwb_q5",
    title: "Scenario: You are waiting in a checkout line for 4 minutes with no immediate tasks. What is your reflex?",
    subtitle: "Micro-boredom tolerance and default device retrieval.",
    type: "scenario",
    dimension: "Notification Resilience",
    options: [
      { id: "dwb_5_a", label: "I observe my surroundings, relax my mind, and let thoughts wander naturally.", value: 5, description: "Mindful presence and boredom tolerance" },
      { id: "dwb_5_b", label: "I wait patiently without looking at screens unless expecting an urgent call.", value: 4, description: "Controlled device independence" },
      { id: "dwb_5_c", label: "I immediately unlock my phone to check feeds or messages.", value: 2, description: "Compulsive default reflex" },
      { id: "dwb_5_d", label: "I juggle switching across 3 social feeds before reaching the cashier.", value: 1, description: "Acute attention fragmentation" },
    ],
  },

  // STAGE 2: Intentional Usage vs Doomscrolling (Questions 6–10)
  {
    id: "dwb_q6",
    title: "How often do you open your phone for a specific reason (e.g. check weather) and realize 20 minutes later that you got sucked into unrelated feeds?",
    subtitle: "Algorithmic rabbit hole susceptibility.",
    type: "frequency",
    dimension: "Intentional Usage",
    reversed: true,
    options: [
      { id: "dwb_6_a", label: "Rarely — I execute my intent and immediately close the device", value: 1 },
      { id: "dwb_6_b", label: "Once or twice a week", value: 2 },
      { id: "dwb_6_c", label: "Daily or several times a day", value: 3 },
      { id: "dwb_6_d", label: "Almost every single time I unlock my screen", value: 4 },
    ],
  },
  {
    id: "dwb_q7",
    title: "I consume digital media with clear conscious intention rather than passive, mindless scrolling.",
    subtitle: "Agency in digital consumption.",
    type: "likert-scale",
    dimension: "Intentional Usage",
    options: [
      { id: "dwb_7_1", label: "Strongly Disagree", value: 1 },
      { id: "dwb_7_2", label: "Disagree", value: 2 },
      { id: "dwb_7_3", label: "Neutral", value: 3 },
      { id: "dwb_7_4", label: "Agree", value: 4 },
      { id: "dwb_7_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "dwb_q8",
    title: "On average, what is your daily non-work screen time on personal mobile devices?",
    subtitle: "Passive entertainment and social consumption volume.",
    type: "single-choice",
    dimension: "Intentional Usage",
    reversed: true, // Higher time = lower score
    options: [
      { id: "dwb_8_a", label: "Under 1.5 hours daily", value: 1 },
      { id: "dwb_8_b", label: "1.5 to 3 hours daily", value: 2 },
      { id: "dwb_8_c", label: "3 to 5 hours daily", value: 3 },
      { id: "dwb_8_d", label: "5+ hours daily", value: 4 },
    ],
  },
  {
    id: "dwb_q9",
    title: "I regularly audit and prune my social follows, newsletters, and apps to eliminate low-value noise.",
    subtitle: "Information diet curation.",
    type: "likert-scale",
    dimension: "Intentional Usage",
    options: [
      { id: "dwb_9_1", label: "Strongly Disagree", value: 1 },
      { id: "dwb_9_2", label: "Disagree", value: 2 },
      { id: "dwb_9_3", label: "Neutral", value: 3 },
      { id: "dwb_9_4", label: "Agree", value: 4 },
      { id: "dwb_9_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "dwb_q10",
    title: "After spending an hour browsing social platforms or video shorts, how do you typically feel?",
    subtitle: "Post-consumption emotional and cognitive aftermath.",
    type: "scenario",
    dimension: "Intentional Usage",
    options: [
      { id: "dwb_10_a", label: "Enriched or entertained with zero regret; I stopped intentionally.", value: 5, description: "Controlled positive utility" },
      { id: "dwb_10_b", label: "Slightly dulled, but aware enough to close the app without distress.", value: 3, description: "Functional satiety" },
      { id: "dwb_10_c", label: "Numb, subtly anxious, and frustrated by wasted time.", value: 2, description: "Regretful consumption hangover" },
      { id: "dwb_10_d", label: "Depleted, envious, and compelled to keep scrolling even while disliking it.", value: 1, description: "Compulsive dissociative loop" },
    ],
  },

  // STAGE 3: Bedtime Disconnect & Sanctuary Protection (Questions 11–15)
  {
    id: "dwb_q11",
    title: "Where do you typically keep your smartphone while you sleep?",
    subtitle: "Physical sleep sanctuary protection from blue light and alerts.",
    type: "single-choice",
    dimension: "Bedtime Disconnect",
    options: [
      { id: "dwb_11_a", label: "Outside the bedroom entirely (or across the room on airplane mode)", value: 5 },
      { id: "dwb_11_b", label: "On a distant dresser across the bedroom", value: 4 },
      { id: "dwb_11_c", label: "On my nightstand directly beside my head", value: 2 },
      { id: "dwb_11_d", label: "Under my pillow or directly in bed with me", value: 1 },
    ],
  },
  {
    id: "dwb_q12",
    title: "How many minutes after waking do you typically check your phone for the first time?",
    subtitle: "Morning dopamine framing and sovereign attention boundary.",
    type: "single-choice",
    dimension: "Bedtime Disconnect",
    options: [
      { id: "dwb_12_a", label: "At least 30–60 minutes after waking (after morning routine)", value: 5 },
      { id: "dwb_12_b", label: "15 to 30 minutes after getting out of bed", value: 4 },
      { id: "dwb_12_c", label: "Within 5 minutes of opening my eyes", value: 2 },
      { id: "dwb_12_d", label: "Immediately — it is the very first thing my hand touches before sitting up", value: 1 },
    ],
  },
  {
    id: "dwb_q13",
    title: "I frequently lose 30+ minutes of sleep because I am absorbed in scrolling before bed.",
    subtitle: "Bedtime revenge procrastination via screen exposure.",
    type: "frequency",
    dimension: "Bedtime Disconnect",
    reversed: true,
    options: [
      { id: "dwb_13_a", label: "Rarely or never", value: 1 },
      { id: "dwb_13_b", label: "Once or twice a month", value: 2 },
      { id: "dwb_13_c", label: "2 to 3 nights per week", value: 3 },
      { id: "dwb_13_d", label: "Almost every single night", value: 4 },
    ],
  },
  {
    id: "dwb_q14",
    title: "I can comfortably enjoy dinner or in-person social events with my phone kept out of sight.",
    subtitle: "Social presence and conversational sanctity.",
    type: "likert-scale",
    dimension: "Bedtime Disconnect",
    options: [
      { id: "dwb_14_1", label: "Strongly Disagree", value: 1 },
      { id: "dwb_14_2", label: "Disagree", value: 2 },
      { id: "dwb_14_3", label: "Neutral", value: 3 },
      { id: "dwb_14_4", label: "Agree", value: 4 },
      { id: "dwb_14_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "dwb_q15",
    title: "My bedroom is a tech-free sanctuary dedicated exclusively to rest, reading, and intimacy.",
    subtitle: "Environmental spatial boundaries.",
    type: "likert-scale",
    dimension: "Bedtime Disconnect",
    options: [
      { id: "dwb_15_1", label: "Strongly Disagree", value: 1 },
      { id: "dwb_15_2", label: "Disagree", value: 2 },
      { id: "dwb_15_3", label: "Neutral", value: 3 },
      { id: "dwb_15_4", label: "Agree", value: 4 },
      { id: "dwb_15_5", label: "Strongly Agree", value: 5 },
    ],
  },

  // STAGE 4: Focus Protection & Attention Depth (Questions 16–20)
  {
    id: "dwb_q16",
    title: "When tackling high-concentration intellectual work, how long can you sustain focus without tab-switching or checking messages?",
    subtitle: "Continuous undivided attention span.",
    type: "single-choice",
    dimension: "Focus Protection",
    options: [
      { id: "dwb_16_a", label: "60–90+ minutes in deep unbroken flow", value: 5 },
      { id: "dwb_16_b", label: "30–45 minutes comfortably", value: 4 },
      { id: "dwb_16_c", label: "10–15 minutes before an itch to check tabs emerges", value: 2 },
      { id: "dwb_16_d", label: "Under 5 minutes — I am in perpetual rapid task-switching", value: 1 },
    ],
  },
  {
    id: "dwb_q17",
    title: "I deliberately schedule 'Do Not Disturb' blocks or airplane mode sessions during priority deep work.",
    subtitle: "Attention defense protocol implementation.",
    type: "likert-scale",
    dimension: "Focus Protection",
    options: [
      { id: "dwb_17_1", label: "Strongly Disagree", value: 1 },
      { id: "dwb_17_2", label: "Disagree", value: 2 },
      { id: "dwb_17_3", label: "Neutral", value: 3 },
      { id: "dwb_17_4", label: "Agree", value: 4 },
      { id: "dwb_17_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "dwb_q18",
    title: "How often do you feel that your attention span and memory are visibly deteriorating due to short-form video or screen overload?",
    subtitle: "Subjective cognitive erosion awareness.",
    type: "frequency",
    dimension: "Focus Protection",
    reversed: true,
    options: [
      { id: "dwb_18_a", label: "Rarely or never", value: 1 },
      { id: "dwb_18_b", label: "Occasionally during stressful weeks", value: 2 },
      { id: "dwb_18_c", label: "Frequently — I struggle to read long articles or books", value: 3 },
      { id: "dwb_18_d", label: "Constantly — my attention feels permanently fractured", value: 4 },
    ],
  },
  {
    id: "dwb_q19",
    title: "I can comfortably read a dense physical book or long-form essay for 45 minutes without feeling restless.",
    subtitle: "Deep reading and cognitive patience capacity.",
    type: "likert-scale",
    dimension: "Focus Protection",
    options: [
      { id: "dwb_19_1", label: "Strongly Disagree", value: 1 },
      { id: "dwb_19_2", label: "Disagree", value: 2 },
      { id: "dwb_19_3", label: "Neutral", value: 3 },
      { id: "dwb_19_4", label: "Agree", value: 4 },
      { id: "dwb_19_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "dwb_q20",
    title: "Overall, who is in control of your digital technology usage?",
    subtitle: "Locus of control in human-device relationship.",
    type: "single-choice",
    dimension: "Focus Protection",
    options: [
      { id: "dwb_20_a", label: "I am — devices serve strictly as intentional tools for my life", value: 5 },
      { id: "dwb_20_b", label: "Mostly myself, with occasional lapses during idle downtime", value: 4 },
      { id: "dwb_20_c", label: "It is an ongoing tug-of-war where apps frequently win my attention", value: 2 },
      { id: "dwb_20_d", label: "Algorithms control my habits and I feel powerless to stop", value: 1 },
    ],
  },
];
