import { Question } from "@/types/question";

export const financialHealthQuestions: Question[] = [
  // STAGE 1: Budget Discipline & Cash Flow Awareness (Questions 1–5)
  {
    id: "fin_q1",
    title: "How accurately do you know your monthly living expenses (rent/mortgage, utilities, food, discretionary)?",
    subtitle: "Cashflow visibility and financial awareness.",
    type: "single-choice",
    dimension: "Budget Discipline",
    options: [
      { id: "fin_1_a", label: "Accurately to within 5% — tracked actively in a spreadsheet or budgeting app", value: 5 },
      { id: "fin_1_b", label: "Reasonably well — I know my general baseline within 10–15%", value: 4 },
      { id: "fin_1_c", label: "Rough estimate — I check my bank balance occasionally to see if I have money", value: 2 },
      { id: "fin_1_d", label: "No idea — I avoid looking at bank statements out of anxiety", value: 1 },
    ],
  },
  {
    id: "fin_q2",
    title: "I consistently spend less than I earn each month, generating a positive savings margin.",
    subtitle: "Living below means and positive savings rate.",
    type: "likert-scale",
    dimension: "Budget Discipline",
    options: [
      { id: "fin_2_1", label: "Strongly Disagree", value: 1 },
      { id: "fin_2_2", label: "Disagree", value: 2 },
      { id: "fin_2_3", label: "Neutral", value: 3 },
      { id: "fin_2_4", label: "Agree", value: 4 },
      { id: "fin_2_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "fin_q3",
    title: "Scenario: You receive an unexpected $1,500 bonus at work. What is your typical action?",
    subtitle: "Windfall allocation habit.",
    type: "scenario",
    dimension: "Budget Discipline",
    options: [
      { id: "fin_3_a", label: "Direct 80%+ toward emergency reserves, debt reduction, or long-term investments.", value: 5, description: "Prudent wealth building" },
      { id: "fin_3_b", label: "Split it: half into savings, half for an intentional reward or trip.", value: 4, description: "Balanced allocation" },
      { id: "fin_3_c", label: "Spend the vast majority on impulse luxury purchases or dining out.", value: 2, description: "Lifestyle consumption inflation" },
      { id: "fin_3_d", label: "It immediately disappears into paying overdue bills with nothing left over.", value: 1, description: "Acute deficit catch-up" },
    ],
  },
  {
    id: "fin_q4",
    title: "I rarely experience overdraft fees, late payment penalties, or bill-checking dread.",
    subtitle: "Financial friction and logistics reliability.",
    type: "likert-scale",
    dimension: "Budget Discipline",
    options: [
      { id: "fin_4_1", label: "Strongly Disagree", value: 1 },
      { id: "fin_4_2", label: "Disagree", value: 2 },
      { id: "fin_4_3", label: "Neutral", value: 3 },
      { id: "fin_4_4", label: "Agree", value: 4 },
      { id: "fin_4_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "fin_q5",
    title: "How frequently do you buy things you cannot comfortably afford using consumer credit?",
    subtitle: "Reverse-scored lifestyle creep indicator.",
    type: "frequency",
    dimension: "Budget Discipline",
    reversed: true,
    options: [
      { id: "fin_5_a", label: "Never", value: 1 },
      { id: "fin_5_b", label: "Rarely (once or twice a year)", value: 2 },
      { id: "fin_5_c", label: "Frequently (monthly)", value: 3 },
      { id: "fin_5_d", label: "Almost every single week", value: 4 },
    ],
  },

  // STAGE 2: Safety Buffer & Emergency Resilience (Questions 6–10)
  {
    id: "fin_q6",
    title: "If all household income stopped today, how many months could you cover essential living expenses from cash reserves?",
    subtitle: "Liquid emergency runway benchmark.",
    type: "single-choice",
    dimension: "Safety Buffer",
    options: [
      { id: "fin_6_a", label: "6+ months of living expenses fully funded in high-yield cash", value: 5 },
      { id: "fin_6_b", label: "3 to 6 months comfortably", value: 4 },
      { id: "fin_6_c", label: "1 to 2 months", value: 2 },
      { id: "fin_6_d", label: "Less than 3 weeks (living paycheck to paycheck)", value: 1 },
    ],
  },
  {
    id: "fin_q7",
    title: "An unexpected $1,000 car repair or medical bill would cause severe financial distress in my life.",
    subtitle: "Reverse-scored shock absorption threshold.",
    type: "likert-scale",
    dimension: "Safety Buffer",
    reversed: true,
    options: [
      { id: "fin_7_1", label: "Strongly Agree", value: 1 },
      { id: "fin_7_2", label: "Agree", value: 2 },
      { id: "fin_7_3", label: "Neutral", value: 3 },
      { id: "fin_7_4", label: "Disagree", value: 4 },
      { id: "fin_7_5", label: "Strongly Disagree", value: 5 },
    ],
  },
  {
    id: "fin_q8",
    title: "Scenario: Your primary laptop or appliance dies unexpectedly tomorrow. How do you pay for the replacement?",
    subtitle: "Liquidity vs emergency debt reliance.",
    type: "scenario",
    dimension: "Safety Buffer",
    options: [
      { id: "fin_8_a", label: "I pay cash from my dedicated emergency fund with zero stress.", value: 5, description: "Self-insured liquidity" },
      { id: "fin_8_b", label: "I charge it to a card and pay it off in full at the next statement.", value: 4, description: "Functional cash flow buffer" },
      { id: "fin_8_c", label: "I put it on high-interest credit card revolving debt and pay it off over months.", value: 2, description: "Debt-financed emergency" },
      { id: "fin_8_d", label: "I cannot afford it and must borrow from family or payday services.", value: 1, description: "Vulnerable emergency state" },
    ],
  },
  {
    id: "fin_q9",
    title: "I maintain appropriate insurance coverage (health, auto, renters/home, disability) to guard against catastrophic loss.",
    subtitle: "Downside risk protection.",
    type: "likert-scale",
    dimension: "Safety Buffer",
    options: [
      { id: "fin_9_1", label: "Strongly Disagree", value: 1 },
      { id: "fin_9_2", label: "Disagree", value: 2 },
      { id: "fin_9_3", label: "Neutral", value: 3 },
      { id: "fin_9_4", label: "Agree", value: 4 },
      { id: "fin_9_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "fin_q10",
    title: "My financial emergency cushion gives me deep psychological peace of mind when career uncertainties arise.",
    subtitle: "Financial buffer psychological security.",
    type: "likert-scale",
    dimension: "Safety Buffer",
    options: [
      { id: "fin_10_1", label: "Strongly Disagree", value: 1 },
      { id: "fin_10_2", label: "Disagree", value: 2 },
      { id: "fin_10_3", label: "Neutral", value: 3 },
      { id: "fin_10_4", label: "Agree", value: 4 },
      { id: "fin_10_5", label: "Strongly Agree", value: 5 },
    ],
  },

  // STAGE 3: Debt Management & Credit Health (Questions 11–15)
  {
    id: "fin_q11",
    title: "Do you carry revolving credit card debt from month to month paying high interest rates (18%+ APR)?",
    subtitle: "High-interest consumer debt load.",
    type: "single-choice",
    dimension: "Debt Management",
    options: [
      { id: "fin_11_a", label: "Never — I pay my full balance automatically every single month", value: 5 },
      { id: "fin_11_b", label: "Rarely — only during rare temporary emergencies", value: 4 },
      { id: "fin_11_c", label: "Occasionally — I carry a balance several months a year", value: 2 },
      { id: "fin_11_d", label: "Constantly — I carry substantial revolving balances paying maximum interest", value: 1 },
    ],
  },
  {
    id: "fin_q12",
    title: "My total debt payments (excluding mortgage) consume less than 15% of my monthly take-home pay.",
    subtitle: "Debt-to-income ratio comfort.",
    type: "likert-scale",
    dimension: "Debt Management",
    options: [
      { id: "fin_12_1", label: "Strongly Disagree", value: 1 },
      { id: "fin_12_2", label: "Disagree", value: 2 },
      { id: "fin_12_3", label: "Neutral", value: 3 },
      { id: "fin_12_4", label: "Agree", value: 4 },
      { id: "fin_12_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "fin_q13",
    title: "I have a clear, active strategy (e.g. avalanche or snowball method) to eliminate any outstanding liabilities.",
    subtitle: "Systematic debt amortization planning.",
    type: "likert-scale",
    dimension: "Debt Management",
    options: [
      { id: "fin_13_1", label: "Strongly Disagree", value: 1 },
      { id: "fin_13_2", label: "Disagree", value: 2 },
      { id: "fin_13_3", label: "Neutral", value: 3 },
      { id: "fin_13_4", label: "Agree", value: 4 },
      { id: "fin_13_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "fin_q14",
    title: "I feel weighed down or trapped in my career because of ongoing debt obligations.",
    subtitle: "Reverse-scored debt-induced existential entrapment.",
    type: "likert-scale",
    dimension: "Debt Management",
    reversed: true,
    options: [
      { id: "fin_14_1", label: "Strongly Agree", value: 1 },
      { id: "fin_14_2", label: "Agree", value: 2 },
      { id: "fin_14_3", label: "Neutral", value: 3 },
      { id: "fin_14_4", label: "Disagree", value: 4 },
      { id: "fin_14_5", label: "Strongly Disagree", value: 5 },
    ],
  },
  {
    id: "fin_q15",
    title: "My credit score is in the 'Good' to 'Excellent' tier (720+), enabling optimal borrowing terms when needed.",
    subtitle: "Credit bureau standing benchmark.",
    type: "single-choice",
    dimension: "Debt Management",
    options: [
      { id: "fin_15_a", label: "Excellent (760+)", value: 5 },
      { id: "fin_15_b", label: "Good (700–759)", value: 4 },
      { id: "fin_15_c", label: "Fair (620–699)", value: 2 },
      { id: "fin_15_d", label: "Poor / Under 620 / Unknown", value: 1 },
    ],
  },

  // STAGE 4: Future Planning & Compounding Wealth (Questions 16–20)
  {
    id: "fin_q16",
    title: "What percentage of your gross income do you systematically invest for long-term retirement and wealth building?",
    subtitle: "Savings and compounding rate benchmark.",
    type: "single-choice",
    dimension: "Future Planning",
    options: [
      { id: "fin_16_a", label: "20%+ consistently automated", value: 5 },
      { id: "fin_16_b", label: "10% to 19% regularly", value: 4 },
      { id: "fin_16_c", label: "3% to 9% intermittently", value: 2 },
      { id: "fin_16_d", label: "0% — I have no retirement or investment accounts", value: 1 },
    ],
  },
  {
    id: "fin_q17",
    title: "My long-term investments are automated (e.g. automatic monthly index fund or 401(k) contributions) so I don't rely on willpower.",
    subtitle: "Automation of compounding wealth.",
    type: "likert-scale",
    dimension: "Future Planning",
    options: [
      { id: "fin_17_1", label: "Strongly Disagree", value: 1 },
      { id: "fin_17_2", label: "Disagree", value: 2 },
      { id: "fin_17_3", label: "Neutral", value: 3 },
      { id: "fin_17_4", label: "Agree", value: 4 },
      { id: "fin_17_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "fin_q18",
    title: "Scenario: Market volatility causes your investment portfolio to decline by 15% over three months. What do you do?",
    subtitle: "Long-term investment psychology.",
    type: "scenario",
    dimension: "Future Planning",
    options: [
      { id: "fin_18_a", label: "I maintain or increase my automatic contributions; market pullbacks are buying opportunities.", value: 5, description: "Disciplined long-term investor" },
      { id: "fin_18_b", label: "I feel slight discomfort but leave my diversified holdings untouched.", value: 4, description: "Resilient passive holder" },
      { id: "fin_18_c", label: "I stop contributions and nervously check my balance daily.", value: 2, description: "Loss aversion hesitation" },
      { id: "fin_18_d", label: "I panic, liquidate to cash at the bottom, and lock in the losses.", value: 1, description: "Emotional capitulation" },
    ],
  },
  {
    id: "fin_q19",
    title: "I have calculated my estimated retirement number or financial independence target.",
    subtitle: "Goal-oriented financial trajectory.",
    type: "likert-scale",
    dimension: "Future Planning",
    options: [
      { id: "fin_19_1", label: "Strongly Disagree", value: 1 },
      { id: "fin_19_2", label: "Disagree", value: 2 },
      { id: "fin_19_3", label: "Neutral", value: 3 },
      { id: "fin_19_4", label: "Agree", value: 4 },
      { id: "fin_19_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "fin_q20",
    title: "Overall, I feel confident, calm, and sovereign regarding my financial future.",
    subtitle: "Financial self-efficacy and holistic mindset.",
    type: "likert-scale",
    dimension: "Future Planning",
    options: [
      { id: "fin_20_1", label: "Strongly Disagree", value: 1 },
      { id: "fin_20_2", label: "Disagree", value: 2 },
      { id: "fin_20_3", label: "Neutral", value: 3 },
      { id: "fin_20_4", label: "Agree", value: 4 },
      { id: "fin_20_5", label: "Strongly Agree", value: 5 },
    ],
  },
];
