import { Question } from "@/types/question";

export const spendingHabitsQuestions: Question[] = [
  // STAGE 1: Impulse Control & Delay Habits (Questions 1–5)
  {
    id: "spn_q1",
    title: "When you see an enticing non-essential item online or in a shop, how do you typically respond?",
    subtitle: "Immediate gratification vs deliberate friction.",
    type: "scenario",
    dimension: "Impulse Control",
    options: [
      { id: "spn_1_a", label: "I implement a mandatory 48-hour or 30-day waiting rule before buying.", value: 5, description: "Controlled delay cooling period" },
      { id: "spn_1_b", label: "I wait a few hours or sleep on it before deciding.", value: 4, description: "Moderate impulse buffer" },
      { id: "spn_1_c", label: "I buy it immediately if it's on sale or marked 'limited quantity'.", value: 2, description: "Scarcity trigger susceptibility" },
      { id: "spn_1_d", label: "I click 1-click buy without second thought and regret it later.", value: 1, description: "Unfiltered impulse purchase" },
    ],
  },
  {
    id: "spn_q2",
    title: "I frequently buy items on flash sales simply because they are discounted, even if I did not need them.",
    subtitle: "Reverse-scored bargain trap vulnerability.",
    type: "frequency",
    dimension: "Impulse Control",
    reversed: true,
    options: [
      { id: "spn_2_a", label: "Never or rarely", value: 1 },
      { id: "spn_2_b", label: "A few times a year", value: 2 },
      { id: "spn_2_c", label: "Monthly", value: 3 },
      { id: "spn_2_d", label: "Multiple times every week", value: 4 },
    ],
  },
  {
    id: "spn_q3",
    title: "I have removed saved credit card autofill and shopping apps from my phone to create friction.",
    subtitle: "Environmental impulse friction design.",
    type: "likert-scale",
    dimension: "Impulse Control",
    options: [
      { id: "spn_3_1", label: "Strongly Disagree", value: 1 },
      { id: "spn_3_2", label: "Disagree", value: 2 },
      { id: "spn_3_3", label: "Neutral", value: 3 },
      { id: "spn_3_4", label: "Agree", value: 4 },
      { id: "spn_3_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "spn_q4",
    title: "I can comfortably walk out of a shopping mall or close an e-commerce site without buying anything.",
    subtitle: "Shopping detachment capacity.",
    type: "likert-scale",
    dimension: "Impulse Control",
    options: [
      { id: "spn_4_1", label: "Strongly Disagree", value: 1 },
      { id: "spn_4_2", label: "Disagree", value: 2 },
      { id: "spn_4_3", label: "Neutral", value: 3 },
      { id: "spn_4_4", label: "Agree", value: 4 },
      { id: "spn_4_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "spn_q5",
    title: "How often do packages arrive at your doorstep that you barely remember ordering or do not feel excited to open?",
    subtitle: "Reverse-scored buyer's remorse frequency.",
    type: "frequency",
    dimension: "Impulse Control",
    reversed: true,
    options: [
      { id: "spn_5_a", label: "Never", value: 1 },
      { id: "spn_5_b", label: "Rarely (once in several months)", value: 2 },
      { id: "spn_5_c", label: "Several times a month", value: 3 },
      { id: "spn_5_d", label: "Regularly every week", value: 4 },
    ],
  },

  // STAGE 2: Value Alignment & Intentional Consumption (Questions 6–10)
  {
    id: "spn_q6",
    title: "When looking over your bank statements from the past 90 days, how closely does your spending reflect your deepest values?",
    subtitle: "Conscious value congruence.",
    type: "single-choice",
    dimension: "Value Alignment",
    options: [
      { id: "spn_6_a", label: "Extremely aligned — nearly every dollar went to health, relationships, learning, or freedom", value: 5 },
      { id: "spn_6_b", label: "Mostly aligned with occasional minor leaks", value: 4 },
      { id: "spn_6_c", label: "Mediocre — substantial money leaked into unmemorable conveniences", value: 2 },
      { id: "spn_6_d", label: "Completely misaligned — I spend money on things that bring zero lasting fulfillment", value: 1 },
    ],
  },
  {
    id: "spn_q7",
    title: "I willingly spend generously on things that deeply enrich my life (e.g. books, quality food, meaningful trips) while cutting ruthlessly on things I do not care about.",
    subtitle: "Ramit Sethi conscious spending philosophy.",
    type: "likert-scale",
    dimension: "Value Alignment",
    options: [
      { id: "spn_7_1", label: "Strongly Disagree", value: 1 },
      { id: "spn_7_2", label: "Disagree", value: 2 },
      { id: "spn_7_3", label: "Neutral", value: 3 },
      { id: "spn_7_4", label: "Agree", value: 4 },
      { id: "spn_7_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "spn_q8",
    title: "I spend money to impress friends, neighbors, or social media followers.",
    subtitle: "Reverse-scored status signaling expenditure.",
    type: "likert-scale",
    dimension: "Value Alignment",
    reversed: true,
    options: [
      { id: "spn_8_1", label: "Strongly Agree", value: 1 },
      { id: "spn_8_2", label: "Agree", value: 2 },
      { id: "spn_8_3", label: "Neutral", value: 3 },
      { id: "spn_8_4", label: "Disagree", value: 4 },
      { id: "spn_8_5", label: "Strongly Disagree", value: 5 },
    ],
  },
  {
    id: "spn_q9",
    title: "I prefer investing in durable, repairable, high-quality possessions over cheap disposable goods.",
    subtitle: "Cost-per-use quality mindset.",
    type: "likert-scale",
    dimension: "Value Alignment",
    options: [
      { id: "spn_9_1", label: "Strongly Disagree", value: 1 },
      { id: "spn_9_2", label: "Disagree", value: 2 },
      { id: "spn_9_3", label: "Neutral", value: 3 },
      { id: "spn_9_4", label: "Agree", value: 4 },
      { id: "spn_9_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "spn_q10",
    title: "My consumption habits are guided by an internal sense of 'enough' rather than endless accumulation.",
    subtitle: "Sufficiency and contentment index.",
    type: "likert-scale",
    dimension: "Value Alignment",
    options: [
      { id: "spn_10_1", label: "Strongly Disagree", value: 1 },
      { id: "spn_10_2", label: "Disagree", value: 2 },
      { id: "spn_10_3", label: "Neutral", value: 3 },
      { id: "spn_10_4", label: "Agree", value: 4 },
      { id: "spn_10_5", label: "Strongly Agree", value: 5 },
    ],
  },

  // STAGE 3: Comparison Shopping & Diligence (Questions 11–15)
  {
    id: "spn_q11",
    title: "Before making a major purchase ($300+), how thoroughly do you research alternatives, reviews, and price history?",
    subtitle: "Pre-purchase diligence benchmark.",
    type: "single-choice",
    dimension: "Comparison Shopping",
    options: [
      { id: "spn_11_a", label: "Extensively — I compare price histories, read independent reviews, and check warranty terms", value: 5 },
      { id: "spn_11_b", label: "Moderately — I check a couple of review sites and verify fair market pricing", value: 4 },
      { id: "spn_11_c", label: "Quick skim — I check 1 review and buy whatever looks popular", value: 2 },
      { id: "spn_11_d", label: "Zero research — I buy the very first sponsored ad result I see", value: 1 },
    ],
  },
  {
    id: "spn_q12",
    title: "I routinely evaluate recurring contracts (internet, insurance, phone plans) annually to negotiate better rates.",
    subtitle: "Fixed overhead optimization.",
    type: "likert-scale",
    dimension: "Comparison Shopping",
    options: [
      { id: "spn_12_1", label: "Strongly Disagree", value: 1 },
      { id: "spn_12_2", label: "Disagree", value: 2 },
      { id: "spn_12_3", label: "Neutral", value: 3 },
      { id: "spn_12_4", label: "Agree", value: 4 },
      { id: "spn_12_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "spn_q13",
    title: "I understand total cost of ownership (maintenance, insurance, subscriptions, repairs) before committing to a purchase.",
    subtitle: "Total lifecycle cost assessment.",
    type: "likert-scale",
    dimension: "Comparison Shopping",
    options: [
      { id: "spn_13_1", label: "Strongly Disagree", value: 1 },
      { id: "spn_13_2", label: "Disagree", value: 2 },
      { id: "spn_13_3", label: "Neutral", value: 3 },
      { id: "spn_13_4", label: "Agree", value: 4 },
      { id: "spn_13_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "spn_q14",
    title: "I calculate costs in terms of working hours required to earn that amount ('Is this jacket worth 6 hours of labor?').",
    subtitle: "Your Money or Your Life labor exchange metric.",
    type: "likert-scale",
    dimension: "Comparison Shopping",
    options: [
      { id: "spn_14_1", label: "Strongly Disagree", value: 1 },
      { id: "spn_14_2", label: "Disagree", value: 2 },
      { id: "spn_14_3", label: "Neutral", value: 3 },
      { id: "spn_14_4", label: "Agree", value: 4 },
      { id: "spn_14_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "spn_q15",
    title: "I am easily swayed by aggressive sales pitches, limited-time countdown timers, or persuasive influencers.",
    subtitle: "Reverse-scored sales pressure susceptibility.",
    type: "likert-scale",
    dimension: "Comparison Shopping",
    reversed: true,
    options: [
      { id: "spn_15_1", label: "Strongly Agree", value: 1 },
      { id: "spn_15_2", label: "Agree", value: 2 },
      { id: "spn_15_3", label: "Neutral", value: 3 },
      { id: "spn_15_4", label: "Disagree", value: 4 },
      { id: "spn_15_5", label: "Strongly Disagree", value: 5 },
    ],
  },

  // STAGE 4: Emotional Spending & Stress Triggers (Questions 16–20)
  {
    id: "spn_q16",
    title: "When experiencing a stressful, exhausting, or emotionally painful day at work, what is your reflex?",
    subtitle: "Retail therapy and emotional coping through spending.",
    type: "scenario",
    dimension: "Emotional Spending",
    reversed: true, // Retail therapy = lower resilience score
    options: [
      { id: "spn_16_a", label: "I decompress through a walk, hot bath, exercise, or talking with someone close.", value: 1, description: "Non-monetary healthy coping" },
      { id: "spn_16_b", label: "I enjoy a modest, planned treat (like a favorite coffee) within my budget.", value: 2, description: "Controlled micro-reward" },
      { id: "spn_16_c", label: "I order expensive takeout and browse shopping sites to soothe my mood.", value: 3, description: "Moderate emotional spending" },
      { id: "spn_16_d", label: "I go on an expensive shopping spree telling myself 'I deserve this after what I went through'.", value: 4, description: "Compulsive compensatory retail therapy" },
    ],
  },
  {
    id: "spn_q17",
    title: "I spend money when feeling bored or lonely as a source of novelty and entertainment.",
    subtitle: "Boredom consumption indicator.",
    type: "frequency",
    dimension: "Emotional Spending",
    reversed: true,
    options: [
      { id: "spn_17_a", label: "Never or rarely", value: 1 },
      { id: "spn_17_b", label: "Occasionally", value: 2 },
      { id: "spn_17_c", label: "Frequently multiple times per month", value: 3 },
      { id: "spn_17_d", label: "Almost every single weekend or evening", value: 4 },
    ],
  },
  {
    id: "spn_q18",
    title: "I feel genuine guilt, regret, or shame after reviewing my unneeded discretionary purchases.",
    subtitle: "Post-purchase emotional dissonance.",
    type: "likert-scale",
    dimension: "Emotional Spending",
    reversed: true,
    options: [
      { id: "spn_18_1", label: "Strongly Agree", value: 1 },
      { id: "spn_18_2", label: "Agree", value: 2 },
      { id: "spn_18_3", label: "Neutral", value: 3 },
      { id: "spn_18_4", label: "Disagree", value: 4 },
      { id: "spn_18_5", label: "Strongly Disagree", value: 5 },
    ],
  },
  {
    id: "spn_q19",
    title: "I hide shopping bags, receipts, or online deliveries from my partner or family members.",
    subtitle: "Financial infidelity and secrecy cues.",
    type: "frequency",
    dimension: "Emotional Spending",
    reversed: true,
    options: [
      { id: "spn_19_a", label: "Never", value: 1 },
      { id: "spn_19_b", label: "Rarely", value: 2 },
      { id: "spn_19_c", label: "Occasionally", value: 3 },
      { id: "spn_19_d", label: "Frequently — I keep secret spending habits", value: 4 },
    ],
  },
  {
    id: "spn_q20",
    title: "Overall, my relationship with money is peaceful, intentional, and free from emotional compulsion.",
    subtitle: "Holistic consumer psychological health.",
    type: "likert-scale",
    dimension: "Emotional Spending",
    options: [
      { id: "spn_20_1", label: "Strongly Disagree", value: 1 },
      { id: "spn_20_2", label: "Disagree", value: 2 },
      { id: "spn_20_3", label: "Neutral", value: 3 },
      { id: "spn_20_4", label: "Agree", value: 4 },
      { id: "spn_20_5", label: "Strongly Agree", value: 5 },
    ],
  },
];
