import { Question } from "@/types/question";

export const timeManagementQuestions: Question[] = [
  // STAGE 1: Priority Setting & Eisenhower Matrix (Questions 1–5)
  {
    id: "tm_q1",
    title: "How do you decide what task to tackle first when beginning your workday?",
    subtitle: "Eisenhower matrix priority discipline.",
    type: "single-choice",
    dimension: "Priority Setting",
    options: [
      { id: "tm_1_a", label: "My most strategically important task, even if no one is nagging me for it", value: 5 },
      { id: "tm_1_b", label: "Whatever deadline is looming closest on the calendar", value: 4 },
      { id: "tm_1_c", label: "The easiest, quickest items to clear them off my plate", value: 2 },
      { id: "tm_1_d", label: "Whatever unread message or email arrived most recently", value: 1 },
    ],
  },
  {
    id: "tm_q2",
    title: "I protect dedicated blocks on my calendar for important non-urgent strategic priorities.",
    subtitle: "Quadrant II investment protection.",
    type: "likert-scale",
    dimension: "Priority Setting",
    options: [
      { id: "tm_2_1", label: "Strongly Disagree", value: 1 },
      { id: "tm_2_2", label: "Disagree", value: 2 },
      { id: "tm_2_3", label: "Neutral", value: 3 },
      { id: "tm_2_4", label: "Agree", value: 4 },
      { id: "tm_2_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "tm_q3",
    title: "How often do you say 'yes' to new commitments without checking your existing calendar capacity?",
    subtitle: "Overcommitment propensity indicator.",
    type: "frequency",
    dimension: "Priority Setting",
    reversed: true,
    options: [
      { id: "tm_3_a", label: "Rarely or never", value: 1 },
      { id: "tm_3_b", label: "Occasionally", value: 2 },
      { id: "tm_3_c", label: "Frequently", value: 3 },
      { id: "tm_3_d", label: "Almost always — I have chronic people-pleasing syndrome", value: 4 },
    ],
  },
  {
    id: "tm_q4",
    title: "Scenario: A non-urgent, interesting idea pops into your head while working on a critical presentation. What do you do?",
    subtitle: "In-flight capture vs tangent derailment.",
    type: "scenario",
    dimension: "Priority Setting",
    options: [
      { id: "tm_4_a", label: "I jot it on a quick capture list in 5 seconds and return immediately to my presentation.", value: 5, description: "Disciplined capture buffer" },
      { id: "tm_4_b", label: "I bookmark a quick tab and finish the presentation first.", value: 4, description: "Effective deferral" },
      { id: "tm_4_c", label: "I spend 40 minutes researching the idea and miss my presentation deadline.", value: 2, description: "Shiny object diversion" },
      { id: "tm_4_d", label: "I abandon my presentation completely to pursue the new rabbit hole.", value: 1, description: "Total priority collapse" },
    ],
  },
  {
    id: "tm_q5",
    title: "I am comfortable delegating or automating tasks that do not require my unique expertise.",
    subtitle: "Leverage and delegation efficiency.",
    type: "likert-scale",
    dimension: "Priority Setting",
    options: [
      { id: "tm_5_1", label: "Strongly Disagree", value: 1 },
      { id: "tm_5_2", label: "Disagree", value: 2 },
      { id: "tm_5_3", label: "Neutral", value: 3 },
      { id: "tm_5_4", label: "Agree", value: 4 },
      { id: "tm_5_5", label: "Strongly Agree", value: 5 },
    ],
  },

  // STAGE 2: Procrastination Shield & Task Initiation (Questions 6–10)
  {
    id: "tm_q6",
    title: "When facing a daunting, ambiguous assignment, how quickly do you initiate the very first step?",
    subtitle: "Activation energy and task initiation latency.",
    type: "single-choice",
    dimension: "Procrastination Shield",
    options: [
      { id: "tm_6_a", label: "Within minutes — I shrink the first action into a tiny 5-minute micro-step", value: 5 },
      { id: "tm_6_b", label: "Within the day after drafting a rough outline", value: 4 },
      { id: "tm_6_c", label: "I delay for several days while experiencing subtle avoidance dread", value: 2 },
      { id: "tm_6_d", label: "I avoid it until the final hours when panic forces action", value: 1 },
    ],
  },
  {
    id: "tm_q7",
    title: "I delay tasks primarily because I demand perfection from my first draft.",
    subtitle: "Perfectionism-driven paralysis indicator.",
    type: "likert-scale",
    dimension: "Procrastination Shield",
    reversed: true,
    options: [
      { id: "tm_7_1", label: "Strongly Agree", value: 1 },
      { id: "tm_7_2", label: "Agree", value: 2 },
      { id: "tm_7_3", label: "Neutral", value: 3 },
      { id: "tm_7_4", label: "Disagree", value: 4 },
      { id: "tm_7_5", label: "Strongly Disagree", value: 5 },
    ],
  },
  {
    id: "tm_q8",
    title: "How frequently do you find yourself 'productively procrastinating' (cleaning desk, organizing files instead of the hard task)?",
    subtitle: "Pseudo-work avoidance pattern.",
    type: "frequency",
    dimension: "Procrastination Shield",
    reversed: true,
    options: [
      { id: "tm_8_a", label: "Rarely or never", value: 1 },
      { id: "tm_8_b", label: "Occasionally once a month", value: 2 },
      { id: "tm_8_c", label: "Weekly whenever hard decisions arise", value: 3 },
      { id: "tm_8_d", label: "Almost daily", value: 4 },
    ],
  },
  {
    id: "tm_q9",
    title: "I use the '2-minute rule' (if a task takes under 2 minutes, do it immediately) effectively.",
    subtitle: "Micro-task clearance velocity.",
    type: "likert-scale",
    dimension: "Procrastination Shield",
    options: [
      { id: "tm_9_1", label: "Strongly Disagree", value: 1 },
      { id: "tm_9_2", label: "Disagree", value: 2 },
      { id: "tm_9_3", label: "Neutral", value: 3 },
      { id: "tm_9_4", label: "Agree", value: 4 },
      { id: "tm_9_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "tm_q10",
    title: "Scenario: You have scheduled 9:00 AM to write a difficult technical report, but feel uninspired when the clock strikes 9:00. What happens?",
    subtitle: "Emotional friction vs procedural commitment.",
    type: "scenario",
    dimension: "Procrastination Shield",
    options: [
      { id: "tm_4_1", label: "I sit down anyway, type bad sentences for 5 minutes, and momentum takes over.", value: 5, description: "Action precedes motivation" },
      { id: "tm_4_2", label: "I review my notes for 10 minutes to ease into the headspace.", value: 4, description: "Gentle ramp-up" },
      { id: "tm_4_3", label: "I tell myself I will wait until afternoon when inspiration strikes.", value: 2, description: "Mood-dependent deferral" },
      { id: "tm_4_4", label: "I push it off until tomorrow and spend the morning answering routine chat.", value: 1, description: "Complete task avoidance" },
    ],
  },

  // STAGE 3: Time Estimation & Planning Accuracy (Questions 11–15)
  {
    id: "tm_q11",
    title: "How accurately do your time estimates match the actual hours required to finish a project?",
    subtitle: "Planning fallacy calibration.",
    type: "single-choice",
    dimension: "Time Estimation",
    options: [
      { id: "tm_11_a", label: "Very accurately — usually within 10–15% of my estimate", value: 5 },
      { id: "tm_11_b", label: "Reasonably close, though complex tasks occasionally run 25% over", value: 4 },
      { id: "tm_11_c", label: "Poorly — tasks consistently take twice as long as I forecast", value: 2 },
      { id: "tm_11_d", label: "Completely inaccurate — I constantly blow past schedules", value: 1 },
    ],
  },
  {
    id: "tm_q12",
    title: "When estimating a project timeline, I systematically factor in buffer time for unexpected hurdles.",
    subtitle: "Hofstadter's Law compensation.",
    type: "likert-scale",
    dimension: "Time Estimation",
    options: [
      { id: "tm_12_1", label: "Strongly Disagree", value: 1 },
      { id: "tm_12_2", label: "Disagree", value: 2 },
      { id: "tm_12_3", label: "Neutral", value: 3 },
      { id: "tm_12_4", label: "Agree", value: 4 },
      { id: "tm_12_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "tm_q13",
    title: "I routinely underestimate the time required for travel, transit, and morning preparations, leading to rushed arrivals.",
    subtitle: "Reverse-scored transition planning error.",
    type: "frequency",
    dimension: "Time Estimation",
    reversed: true,
    options: [
      { id: "tm_13_a", label: "Rarely or never", value: 1 },
      { id: "tm_13_b", label: "Once or twice a month", value: 2 },
      { id: "tm_13_c", label: "Weekly", value: 3 },
      { id: "tm_13_d", label: "Almost every time I leave the house", value: 4 },
    ],
  },
  {
    id: "tm_q14",
    title: "I break multi-week projects into granular time-estimated sub-tasks rather than a single monolithic deadline.",
    subtitle: "Granular work breakdown structure.",
    type: "likert-scale",
    dimension: "Time Estimation",
    options: [
      { id: "tm_14_1", label: "Strongly Disagree", value: 1 },
      { id: "tm_14_2", label: "Disagree", value: 2 },
      { id: "tm_14_3", label: "Neutral", value: 3 },
      { id: "tm_14_4", label: "Agree", value: 4 },
      { id: "tm_14_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "tm_q15",
    title: "Scenario: A client asks: 'Can you deliver this major deliverable by tomorrow 5 PM?' It realistically requires 14 hours of work.",
    subtitle: "Estimation integrity under client pressure.",
    type: "scenario",
    dimension: "Time Estimation",
    options: [
      { id: "tm_15_a", label: "I provide an honest timeline: 'To maintain quality, Friday at 12 PM is the realistic delivery date.'", value: 5, description: "Professional integrity boundary" },
      { id: "tm_15_b", label: "I offer a phased delivery: core outline tomorrow, full polish by Thursday.", value: 4, description: "Constructive scope negotiation" },
      { id: "tm_15_c", label: "I say yes in the moment, then pull a grueling all-nighter with subpar work.", value: 2, description: "Compliance at expense of health and quality" },
      { id: "tm_15_d", label: "I say yes, miss the deadline entirely, and make up excuses tomorrow.", value: 1, description: "Overpromise and default" },
    ],
  },

  // STAGE 4: Buffer Discipline & Schedule Architecture (Questions 16–20)
  {
    id: "tm_q16",
    title: "How many back-to-back meetings or obligations do you schedule without breathing room?",
    subtitle: "Calendar white-space protection.",
    type: "single-choice",
    dimension: "Buffer Discipline",
    reversed: true, // Back-to-back = lower score
    options: [
      { id: "tm_16_a", label: "None — I mandate 15–30 minute buffers between every commitment", value: 1 },
      { id: "tm_16_b", label: "Occasionally 2 in a row, but never 3+", value: 2 },
      { id: "tm_16_c", label: "Often 3 to 4 back-to-back blocks", value: 3 },
      { id: "tm_16_d", label: "My calendar is a solid wall of back-to-back blocks daily", value: 4 },
    ],
  },
  {
    id: "tm_q17",
    title: "I deliberately leave at least 20% of my weekly schedule open for emergent crises and unscripted recovery.",
    subtitle: "Margin buffer theory.",
    type: "likert-scale",
    dimension: "Buffer Discipline",
    options: [
      { id: "tm_17_1", label: "Strongly Disagree", value: 1 },
      { id: "tm_17_2", label: "Disagree", value: 2 },
      { id: "tm_17_3", label: "Neutral", value: 3 },
      { id: "tm_17_4", label: "Agree", value: 4 },
      { id: "tm_17_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "tm_q18",
    title: "When an unexpected urgency completely consumes your Tuesday morning, what happens to the rest of your week?",
    subtitle: "Schedule elasticity and cascade resilience.",
    type: "scenario",
    dimension: "Buffer Discipline",
    options: [
      { id: "tm_18_a", label: "My buffers absorb the shock; non-critical items shift gracefully without panic.", value: 5, description: "Elastic buffer absorption" },
      { id: "tm_18_b", label: "I work 1 hour late to catch up and the rest of the week holds steady.", value: 4, description: "Targeted minor compensation" },
      { id: "tm_18_c", label: "My whole week descends into a chaotic dominos collapse of late deadlines.", value: 2, description: "Fragile zero-buffer cascade" },
      { id: "tm_18_d", label: "I feel totally defeated and give up on my weekly goals entirely.", value: 1, description: "Catastrophic collapse" },
    ],
  },
  {
    id: "tm_q19",
    title: "I consistently arrive at meetings and appointments 3 to 5 minutes early with zero rush.",
    subtitle: "Punctuality and margin habits.",
    type: "likert-scale",
    dimension: "Buffer Discipline",
    options: [
      { id: "tm_19_1", label: "Strongly Disagree", value: 1 },
      { id: "tm_19_2", label: "Disagree", value: 2 },
      { id: "tm_19_3", label: "Neutral", value: 3 },
      { id: "tm_19_4", label: "Agree", value: 4 },
      { id: "tm_19_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "tm_q20",
    title: "Overall, my schedule feels spacious, intentional, and sustainable rather than frantic and suffocating.",
    subtitle: "Holistic time sovereignty perception.",
    type: "likert-scale",
    dimension: "Buffer Discipline",
    options: [
      { id: "tm_20_1", label: "Strongly Disagree", value: 1 },
      { id: "tm_20_2", label: "Disagree", value: 2 },
      { id: "tm_20_3", label: "Neutral", value: 3 },
      { id: "tm_20_4", label: "Agree", value: 4 },
      { id: "tm_20_5", label: "Strongly Agree", value: 5 },
    ],
  },
];
