import { Question } from "@/types/question";

export const communicationQuestions: Question[] = [
  // STAGE 1: Conversational Defaults & Communication Stance (Questions 1–5)
  {
    id: "com_q1",
    title: "When explaining a complex issue or assigning a task, what is your primary objective?",
    subtitle: "Conversational framing style.",
    type: "single-choice",
    dimension: "Directness",
    options: [
      { id: "com_1_a", label: "State expectations directly with absolute clarity and measurable deadlines.", value: 5 },
      { id: "com_1_b", label: "Check in on their workload and emotional bandwidth before discussing the task.", value: 3 },
      { id: "com_1_c", label: "Frame the request gently with polite qualifiers so they don't feel pressured.", value: 3 },
      { id: "com_1_d", label: "Drop subtle hints and hope they infer what needs to get done.", value: 1 },
    ],
  },
  {
    id: "com_q2",
    title: "I genuinely give my full undivided attention when someone speaks, without mentally formulating my counterargument.",
    subtitle: "Non-judgmental active listening capacity.",
    type: "likert-scale",
    dimension: "Empathetic Listening",
    options: [
      { id: "com_2_1", label: "Strongly Disagree", value: 1 },
      { id: "com_2_2", label: "Disagree", value: 2 },
      { id: "com_2_3", label: "Neutral", value: 3 },
      { id: "com_2_4", label: "Agree", value: 4 },
      { id: "com_2_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "com_q3",
    title: "I can rephrase sensitive criticism into constructive, collaborative suggestions that preserve others' dignity.",
    subtitle: "Tactful diplomatic framing.",
    type: "likert-scale",
    dimension: "Diplomacy",
    options: [
      { id: "com_3_1", label: "Strongly Disagree", value: 1 },
      { id: "com_3_2", label: "Disagree", value: 2 },
      { id: "com_3_3", label: "Neutral", value: 3 },
      { id: "com_3_4", label: "Agree", value: 4 },
      { id: "com_3_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "com_q4",
    title: "I quickly notice micro-expressions, posture shifts, and vocal cadence changes when someone is uncomfortable.",
    subtitle: "Nonverbal cue perception.",
    type: "likert-scale",
    dimension: "Nonverbal Sensitivity",
    options: [
      { id: "com_4_1", label: "Strongly Disagree", value: 1 },
      { id: "com_4_2", label: "Disagree", value: 2 },
      { id: "com_4_3", label: "Neutral", value: 3 },
      { id: "com_4_4", label: "Agree", value: 4 },
      { id: "com_4_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "com_q5",
    title: "I avoid beating around the bush; I address difficult elephants in the room promptly and honestly.",
    subtitle: "Proactive candid confrontation.",
    type: "likert-scale",
    dimension: "Directness",
    options: [
      { id: "com_5_1", label: "Strongly Disagree", value: 1 },
      { id: "com_5_2", label: "Disagree", value: 2 },
      { id: "com_5_3", label: "Neutral", value: 3 },
      { id: "com_5_4", label: "Agree", value: 4 },
      { id: "com_5_5", label: "Strongly Agree", value: 5 },
    ],
  },

  // STAGE 2: Behavioral Listening & Verbal Habits (Questions 6–10)
  {
    id: "com_q6",
    title: "How often do you interrupt or finish other people's sentences before they complete their thought?",
    subtitle: "Conversational pacing and conversational turn-taking.",
    type: "frequency",
    dimension: "Empathetic Listening",
    reversed: true,
    options: [
      { id: "com_6_a", label: "Never or rarely", value: 1 },
      { id: "com_6_b", label: "Occasionally when excited", value: 2 },
      { id: "com_6_c", label: "Frequently throughout the day", value: 3 },
      { id: "com_6_d", label: "Almost always — I process faster than they speak", value: 4 },
    ],
  },
  {
    id: "com_q7",
    title: "In heated group disagreements, I work to find common middle ground and de-escalate tension.",
    subtitle: "Consensus mediation instinct.",
    type: "likert-scale",
    dimension: "Diplomacy",
    options: [
      { id: "com_7_1", label: "Strongly Disagree", value: 1 },
      { id: "com_7_2", label: "Disagree", value: 2 },
      { id: "com_7_3", label: "Neutral", value: 3 },
      { id: "com_7_4", label: "Agree", value: 4 },
      { id: "com_7_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "com_q8",
    title: "I consciously adjust my own vocal volume, body posture, and eye contact to put conversation partners at ease.",
    subtitle: "Nonverbal mirroring and regulation.",
    type: "likert-scale",
    dimension: "Nonverbal Sensitivity",
    options: [
      { id: "com_8_1", label: "Strongly Disagree", value: 1 },
      { id: "com_8_2", label: "Disagree", value: 2 },
      { id: "com_8_3", label: "Neutral", value: 3 },
      { id: "com_8_4", label: "Agree", value: 4 },
      { id: "com_8_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "com_q9",
    title: "I am comfortable saying a clear, unapologetic 'no' to requests that exceed my capacity or violate my boundaries.",
    subtitle: "Assertive boundary setting.",
    type: "likert-scale",
    dimension: "Directness",
    options: [
      { id: "com_9_1", label: "Strongly Disagree", value: 1 },
      { id: "com_9_2", label: "Disagree", value: 2 },
      { id: "com_9_3", label: "Neutral", value: 3 },
      { id: "com_9_4", label: "Agree", value: 4 },
      { id: "com_9_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "com_q10",
    title: "When someone shares a personal problem, I summarize their feelings first ('It sounds like you felt betrayed') rather than jumping straight to solutions.",
    subtitle: "Emotional reflection validation.",
    type: "likert-scale",
    dimension: "Empathetic Listening",
    options: [
      { id: "com_10_1", label: "Strongly Disagree", value: 1 },
      { id: "com_10_2", label: "Disagree", value: 2 },
      { id: "com_10_3", label: "Neutral", value: 3 },
      { id: "com_10_4", label: "Agree", value: 4 },
      { id: "com_10_5", label: "Strongly Agree", value: 5 },
    ],
  },

  // STAGE 3: Situational Conflict & Critical Feedback (Questions 11–15)
  {
    id: "com_q11",
    title: "A colleague delivers subpar work that jeopardizes your mutual deadline. How do you respond?",
    subtitle: "Dilemma: Candor vs sensitivity balance.",
    type: "scenario",
    dimension: "Diplomacy",
    options: [
      { id: "com_11_a", label: "Schedule a private 1-on-1, highlight specific gaps objectively, and co-create an expedited fix.", value: 5 },
      { id: "com_11_b", label: "Call them out immediately in the group channel so they learn accountability.", value: 2 },
      { id: "com_11_c", label: "Quietly redo all their work yourself in secret to avoid awkward friction.", value: 2 },
      { id: "com_11_d", label: "Complain about them to other coworkers behind their back.", value: 1 },
    ],
  },
  {
    id: "com_q12",
    title: "I can sense the emotional undercurrent of a meeting room within minutes of walking in, even before words are spoken.",
    subtitle: "Atmospheric social intuition.",
    type: "likert-scale",
    dimension: "Nonverbal Sensitivity",
    options: [
      { id: "com_12_1", label: "Strongly Disagree", value: 1 },
      { id: "com_12_2", label: "Disagree", value: 2 },
      { id: "com_12_3", label: "Neutral", value: 3 },
      { id: "com_12_4", label: "Agree", value: 4 },
      { id: "com_12_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "com_q13",
    title: "When giving feedback, I separate specific behaviors from personal character traits.",
    subtitle: "Objective behavioral critique.",
    type: "likert-scale",
    dimension: "Directness",
    options: [
      { id: "com_13_1", label: "Strongly Disagree", value: 1 },
      { id: "com_13_2", label: "Disagree", value: 2 },
      { id: "com_13_3", label: "Neutral", value: 3 },
      { id: "com_13_4", label: "Agree", value: 4 },
      { id: "com_13_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "com_q14",
    title: "I ask open-ended clarifying questions ('Can you say more about what led to that?') instead of making rapid assumptions.",
    subtitle: "Inquiry over advocacy balance.",
    type: "likert-scale",
    dimension: "Empathetic Listening",
    options: [
      { id: "com_14_1", label: "Strongly Disagree", value: 1 },
      { id: "com_14_2", label: "Disagree", value: 2 },
      { id: "com_14_3", label: "Neutral", value: 3 },
      { id: "com_14_4", label: "Agree", value: 4 },
      { id: "com_14_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "com_q15",
    title: "I can effectively disagree with authority figures or high-status clients without triggering defensiveness.",
    subtitle: "Tactful dissent delivery.",
    type: "likert-scale",
    dimension: "Diplomacy",
    options: [
      { id: "com_15_1", label: "Strongly Disagree", value: 1 },
      { id: "com_15_2", label: "Disagree", value: 2 },
      { id: "com_15_3", label: "Neutral", value: 3 },
      { id: "com_15_4", label: "Agree", value: 4 },
      { id: "com_15_5", label: "Strongly Agree", value: 5 },
    ],
  },

  // STAGE 4: High-Stakes Communication & Emotional Regulation (Questions 16–20)
  {
    id: "com_q16",
    title: "I notice when my own physical gestures (crossed arms, sighing, foot tapping) might project hostility or boredom.",
    subtitle: "Self-referential nonverbal calibration.",
    type: "likert-scale",
    dimension: "Nonverbal Sensitivity",
    options: [
      { id: "com_16_1", label: "Strongly Disagree", value: 1 },
      { id: "com_16_2", label: "Disagree", value: 2 },
      { id: "com_16_3", label: "Neutral", value: 3 },
      { id: "com_16_4", label: "Agree", value: 4 },
      { id: "com_16_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "com_q17",
    title: "I express my core needs and bottom lines explicitly rather than expecting others to read my mind.",
    subtitle: "Clarity of personal needs.",
    type: "likert-scale",
    dimension: "Directness",
    options: [
      { id: "com_17_1", label: "Strongly Disagree", value: 1 },
      { id: "com_17_2", label: "Disagree", value: 2 },
      { id: "com_17_3", label: "Neutral", value: 3 },
      { id: "com_17_4", label: "Agree", value: 4 },
      { id: "com_17_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "com_q18",
    title: "Even when I strongly disagree with someone's viewpoint, I can validate their right to hold that emotion.",
    subtitle: "Cognitive perspective validation.",
    type: "likert-scale",
    dimension: "Empathetic Listening",
    options: [
      { id: "com_18_1", label: "Strongly Disagree", value: 1 },
      { id: "com_18_2", label: "Disagree", value: 2 },
      { id: "com_18_3", label: "Neutral", value: 3 },
      { id: "com_18_4", label: "Agree", value: 4 },
      { id: "com_18_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "com_q19",
    title: "In contentious debates, I search for the 10% of truth in the other person's argument before attacking flaws.",
    subtitle: "Steel-manning and diplomatic bridge-building.",
    type: "likert-scale",
    dimension: "Diplomacy",
    options: [
      { id: "com_19_1", label: "Strongly Disagree", value: 1 },
      { id: "com_19_2", label: "Disagree", value: 2 },
      { id: "com_19_3", label: "Neutral", value: 3 },
      { id: "com_19_4", label: "Agree", value: 4 },
      { id: "com_19_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "com_q20",
    title: "I can distinguish between what is explicitly said and what is communicated through silence and tone.",
    subtitle: "Subtext comprehension mastery.",
    type: "likert-scale",
    dimension: "Nonverbal Sensitivity",
    options: [
      { id: "com_20_1", label: "Strongly Disagree", value: 1 },
      { id: "com_20_2", label: "Disagree", value: 2 },
      { id: "com_20_3", label: "Neutral", value: 3 },
      { id: "com_20_4", label: "Agree", value: 4 },
      { id: "com_20_5", label: "Strongly Agree", value: 5 },
    ],
  },
];
