import { Question } from "@/types/question";

export const iqQuestions: Question[] = [
  // STAGE 1: Visual Logic & Foundational Patterns (Questions 1–5)
  {
    id: "iq_q1",
    title: "Which element logically completes the pattern: Circle, Square, Circle, Square, Circle, ...?",
    subtitle: "Identify the immediate repeating alternating sequence.",
    type: "single-choice",
    dimension: "Visual Logic",
    options: [
      { id: "iq_1_a", label: "Triangle", value: 0 },
      { id: "iq_1_b", label: "Square", value: 5, description: "Correct alternating shape" },
      { id: "iq_1_c", label: "Circle", value: 0 },
      { id: "iq_1_d", label: "Pentagon", value: 0 },
    ],
  },
  {
    id: "iq_q2",
    title: "A 3x3 grid displays shaded cells in the top row: [1st cell, 2nd cell, 3rd cell]. Next row: [2nd cell, 3rd cell, 1st cell]. What should the 3rd row start with to maintain cyclical shift?",
    subtitle: "Notice the horizontal leftward wrap-around shift.",
    type: "single-choice",
    dimension: "Visual Logic",
    options: [
      { id: "iq_2_a", label: "1st cell", value: 0 },
      { id: "iq_2_b", label: "2nd cell", value: 0 },
      { id: "iq_2_c", label: "3rd cell", value: 5, description: "Maintains cyclic permutation [3, 1, 2]" },
      { id: "iq_2_d", label: "All cells unshaded", value: 0 },
    ],
  },
  {
    id: "iq_q3",
    title: "Consider the symmetry: Shape A points North. Shape B points East. Shape C points South. Which direction must Shape D point to complete a 90° clockwise cycle?",
    subtitle: "Rotational progression in 2D space.",
    type: "single-choice",
    dimension: "Visual Logic",
    options: [
      { id: "iq_3_a", label: "West", value: 5, description: "Completes the 360-degree rotation" },
      { id: "iq_3_b", label: "North-West", value: 0 },
      { id: "iq_3_c", label: "South-West", value: 0 },
      { id: "iq_3_d", label: "North", value: 0 },
    ],
  },
  {
    id: "iq_q4",
    title: "When inspecting overlapping transparent geometric figures, how easily do you isolate intersecting intersections?",
    subtitle: "Self-perceived figure-ground segregation ability.",
    type: "likert-scale",
    dimension: "Visual Logic",
    options: [
      { id: "iq_4_1", label: "Very Difficult", value: 1 },
      { id: "iq_4_2", label: "Somewhat Difficult", value: 2 },
      { id: "iq_4_3", label: "Moderate", value: 3 },
      { id: "iq_4_4", label: "Easy", value: 4 },
      { id: "iq_4_5", label: "Effortless", value: 5 },
    ],
  },
  {
    id: "iq_q5",
    title: "Rule check: In an inverted matrix, if White becomes Black and Dots become Crosses, what does a White square with a Dot become?",
    subtitle: "Simultaneous dual-rule transformation.",
    type: "single-choice",
    dimension: "Visual Logic",
    options: [
      { id: "iq_5_a", label: "Black square with a Dot", value: 0 },
      { id: "iq_5_b", label: "White square with a Cross", value: 0 },
      { id: "iq_5_c", label: "Black square with a Cross", value: 5, description: "Both color inversion and symbol swap applied" },
      { id: "iq_5_d", label: "Grey square with no inner symbol", value: 0 },
    ],
  },

  // STAGE 2: Sequence Analysis & Progression Rules (Questions 6–10)
  {
    id: "iq_q6",
    title: "What number comes next in the progression: 2, 6, 12, 20, 30, ...?",
    subtitle: "Observe the differences: +4, +6, +8, +10...",
    type: "single-choice",
    dimension: "Sequence Analysis",
    options: [
      { id: "iq_6_a", label: "40", value: 0 },
      { id: "iq_6_b", label: "42", value: 5, description: "30 + 12 = 42" },
      { id: "iq_6_c", label: "44", value: 0 },
      { id: "iq_6_d", label: "48", value: 0 },
    ],
  },
  {
    id: "iq_q7",
    title: "Identify the missing value in this alternating series: 100, 2, 90, 4, 80, 8, [ ? ], 16",
    subtitle: "Two interleaved sequences: one decreasing by 10, one doubling.",
    type: "single-choice",
    dimension: "Sequence Analysis",
    options: [
      { id: "iq_7_a", label: "70", value: 5, description: "Interleaved 100 -> 90 -> 80 -> 70" },
      { id: "iq_7_b", label: "75", value: 0 },
      { id: "iq_7_c", label: "60", value: 0 },
      { id: "iq_7_d", label: "12", value: 0 },
    ],
  },
  {
    id: "iq_q8",
    title: "Alphabetical progression: A, C, F, J, O, ... What is the next letter?",
    subtitle: "Increments in alphabet rank: +2, +3, +4, +5, ...",
    type: "single-choice",
    dimension: "Sequence Analysis",
    options: [
      { id: "iq_8_a", label: "S", value: 0 },
      { id: "iq_8_b", label: "T", value: 0 },
      { id: "iq_8_c", label: "U", value: 5, description: "O is 15th letter, 15 + 6 = 21 (U)" },
      { id: "iq_8_d", label: "V", value: 0 },
    ],
  },
  {
    id: "iq_q9",
    title: "I often notice mathematical and structural patterns in everyday data or timestamps without conscious effort.",
    subtitle: "Spontaneous pattern detection propensity.",
    type: "likert-scale",
    dimension: "Sequence Analysis",
    options: [
      { id: "iq_9_1", label: "Rarely / Never", value: 1 },
      { id: "iq_9_2", label: "Seldom", value: 2 },
      { id: "iq_9_3", label: "Occasionally", value: 3 },
      { id: "iq_9_4", label: "Frequently", value: 4 },
      { id: "iq_9_5", label: "Almost Always", value: 5 },
    ],
  },
  {
    id: "iq_q10",
    title: "Fibonacci-variant sequence: 3, 5, 8, 13, 21, [ ? ]",
    subtitle: "Sum of the two preceding terms.",
    type: "single-choice",
    dimension: "Sequence Analysis",
    options: [
      { id: "iq_10_a", label: "31", value: 0 },
      { id: "iq_10_b", label: "33", value: 0 },
      { id: "iq_10_c", label: "34", value: 5, description: "13 + 21 = 34" },
      { id: "iq_10_d", label: "37", value: 0 },
    ],
  },

  // STAGE 3: Spatial Deduction & Mental Transformation (Questions 11–15)
  {
    id: "iq_q11",
    title: "If a standard 6-sided die is unfolded into a cross with '1' at the center, and opposite sides always sum to 7, which number must be directly on the opposite side to 1?",
    subtitle: "Spatial cube folding rule.",
    type: "single-choice",
    dimension: "Spatial Deduction",
    options: [
      { id: "iq_11_a", label: "6", value: 5, description: "1 + 6 = 7" },
      { id: "iq_11_b", label: "5", value: 0 },
      { id: "iq_11_c", label: "4", value: 0 },
      { id: "iq_11_d", label: "2", value: 0 },
    ],
  },
  {
    id: "iq_q12",
    title: "Imagine folding a square sheet of paper in half from left to right, then punching a hole in the top-right corner. When fully unfolded, where are the holes?",
    subtitle: "Symmetry reflection across vertical fold axis.",
    type: "single-choice",
    dimension: "Spatial Deduction",
    options: [
      { id: "iq_12_a", label: "One hole in the top right only", value: 0 },
      { id: "iq_12_b", label: "Two holes: top-right and top-left corners", value: 5, description: "Symmetric reflection across central vertical fold line" },
      { id: "iq_12_c", label: "Two holes: top-right and bottom-right corners", value: 0 },
      { id: "iq_12_d", label: "Four holes: all four corners", value: 0 },
    ],
  },
  {
    id: "iq_q13",
    title: "How easily can you mentally rotate 3D objects to determine if two silhouettes are identical or mirror images?",
    subtitle: "Mental rotation and spatial orientation facility.",
    type: "likert-scale",
    dimension: "Spatial Deduction",
    options: [
      { id: "iq_13_1", label: "Extremely difficult", value: 1 },
      { id: "iq_13_2", label: "Slow and requires re-checking", value: 2 },
      { id: "iq_13_3", label: "Comfortable with simple shapes", value: 3 },
      { id: "iq_13_4", label: "Fluent with complex structures", value: 4 },
      { id: "iq_13_5", label: "Immediate and vivid mental representation", value: 5 },
    ],
  },
  {
    id: "iq_q14",
    title: "A clock shows 3:15. If the entire clock is viewed through a vertical flat mirror, what time does the reflection appear to show?",
    subtitle: "Horizontal inversion of clock hands.",
    type: "single-choice",
    dimension: "Spatial Deduction",
    options: [
      { id: "iq_14_a", label: "8:45", value: 5, description: "Minute hand at 3 reflects to 9; hour hand slightly past 3 reflects to slightly before 9" },
      { id: "iq_14_b", label: "9:15", value: 0 },
      { id: "iq_14_c", label: "3:45", value: 0 },
      { id: "iq_14_d", label: "9:45", value: 0 },
    ],
  },
  {
    id: "iq_q15",
    title: "Gear A (with 20 teeth) meshes directly with Gear B (with 40 teeth). If Gear A rotates 2 full revolutions clockwise, how does Gear B rotate?",
    subtitle: "Mechanical ratio and counter-directional rotation.",
    type: "single-choice",
    dimension: "Spatial Deduction",
    options: [
      { id: "iq_15_a", label: "1 revolution counter-clockwise", value: 5, description: "Inverse direction and half the revolutions due to 2:1 gear ratio" },
      { id: "iq_15_b", label: "2 revolutions counter-clockwise", value: 0 },
      { id: "iq_15_c", label: "1 revolution clockwise", value: 0 },
      { id: "iq_15_d", label: "4 revolutions counter-clockwise", value: 0 },
    ],
  },

  // STAGE 4: Cognitive Speed & Multi-Rule Synthesis (Questions 16–20)
  {
    id: "iq_q16",
    title: "Premise 1: All Zips are Zops. Premise 2: Some Zops are Zaps. Premise 3: No Zap is a Zip. Can a Zap be a Zop?",
    subtitle: "Formal syllogistic deduction.",
    type: "single-choice",
    dimension: "Cognitive Speed",
    options: [
      { id: "iq_16_a", label: "Yes, definitely", value: 5, description: "Directly affirmed by Premise 2 ('Some Zops are Zaps')" },
      { id: "iq_16_b", label: "No, impossible", value: 0 },
      { id: "iq_16_c", label: "Only if Zips are Zaps", value: 0 },
      { id: "iq_16_d", label: "Cannot be determined", value: 0 },
    ],
  },
  {
    id: "iq_q17",
    title: "Scenario: You are presented with an unfamiliar complex diagram containing 4 nested interdependent logical conditions under time pressure.",
    subtitle: "What is your natural operational strategy?",
    type: "scenario",
    dimension: "Cognitive Speed",
    options: [
      { id: "iq_17_1", label: "Deconstruct the outermost constraints first, isolating one variable at a time.", value: 5, description: "Structured analytical decoupling" },
      { id: "iq_17_2", label: "Scan the overall visual rhythm to spot anomalies before checking specifics.", value: 4, description: "Heuristic holistic parsing" },
      { id: "iq_17_3", label: "Guess probable answers based on partial similarities to previous problems.", value: 2, description: "Heuristic approximation without complete validation" },
      { id: "iq_17_4", label: "Re-read the instructions repeatedly until the pressure causes fatigue.", value: 1, description: "Analysis paralysis under constraint" },
    ],
  },
  {
    id: "iq_q18",
    title: "I often hesitate and lose momentum when problems require holding multiple abstract rules in working memory at once.",
    subtitle: "Reverse-scored working memory load indicator.",
    type: "likert-scale",
    dimension: "Cognitive Speed",
    reversed: true, // Reverse scored: Strongly Disagree yields maximum points
    options: [
      { id: "iq_18_1", label: "Strongly Agree", value: 1 },
      { id: "iq_18_2", label: "Agree", value: 2 },
      { id: "iq_18_3", label: "Neutral", value: 3 },
      { id: "iq_18_4", label: "Disagree", value: 4 },
      { id: "iq_18_5", label: "Strongly Disagree", value: 5 },
    ],
  },
  {
    id: "iq_q19",
    title: "A code replaces letters by their reversed position in the alphabet: A=Z, B=Y, C=X. What does the word 'GLOW' encode to? (Note: G=20th from end=T, L=15th=O, O=12th=L, W=4th=D)",
    subtitle: "Rapid symbolic translation under constraint.",
    type: "single-choice",
    dimension: "Cognitive Speed",
    options: [
      { id: "iq_19_a", label: "TOLD", value: 5, description: "G->T, L->O, O->L, W->D" },
      { id: "iq_19_b", label: "SOLD", value: 0 },
      { id: "iq_19_c", label: "TOLE", value: 0 },
      { id: "iq_19_d", label: "TLOD", value: 0 },
    ],
  },
  {
    id: "iq_q20",
    title: "Final Synthesis: In a sequence where shape sides multiply by 2 (Triangle [3], Hexagon [6], Dodecagon [12]), and shading alternates (Solid, Striped, Solid), what is the 4th figure?",
    subtitle: "Combined geometric vertex multiplication and periodic shading.",
    type: "single-choice",
    dimension: "Cognitive Speed",
    options: [
      { id: "iq_20_a", label: "A 24-sided polygon with Striped shading", value: 5, description: "12 * 2 = 24 sides, alternating shading is Striped" },
      { id: "iq_20_b", label: "A 24-sided polygon with Solid shading", value: 0 },
      { id: "iq_20_c", label: "An 18-sided polygon with Striped shading", value: 0 },
      { id: "iq_20_d", label: "A 16-sided polygon with Empty shading", value: 0 },
    ],
  },
];
