import { Question } from "@/types/question";

export const relationshipQuestions: Question[] = [
  // STAGE 1: Everyday Connection & Foundation (Questions 1–5)
  {
    id: "rel_q1",
    title: "When your partner (or someone very close to you) shares good news or a personal victory, how do you typically react?",
    subtitle: "Active-constructive responding and celebration.",
    type: "scenario",
    dimension: "Emotional Attunement",
    options: [
      { id: "rel_1_a", label: "I celebrate enthusiastically, ask curious follow-up questions, and share their joy wholeheartedly.", value: 5, description: "Active-constructive" },
      { id: "rel_1_b", label: "I offer a warm smile and a brief 'That's great, congratulations!'.", value: 4, description: "Passive-constructive" },
      { id: "rel_1_c", label: "I point out the potential downsides or risks of their news.", value: 2, description: "Active-destructive" },
      { id: "rel_1_d", label: "I barely acknowledge it and pivot the conversation back to my own day.", value: 1, description: "Passive-destructive" },
    ],
  },
  {
    id: "rel_q2",
    title: "In moments of disagreement, we focus on resolving the specific problem rather than attacking each other's character.",
    subtitle: "Separation of conflict issue from partner worth.",
    type: "likert-scale",
    dimension: "Constructive Conflict",
    options: [
      { id: "rel_2_1", label: "Strongly Disagree", value: 1 },
      { id: "rel_2_2", label: "Disagree", value: 2 },
      { id: "rel_2_3", label: "Neutral", value: 3 },
      { id: "rel_2_4", label: "Agree", value: 4 },
      { id: "rel_2_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "rel_q3",
    title: "My partner and I share compatible views on fundamental life questions (money, lifestyle, family, ethics).",
    subtitle: "Core value alignment baseline.",
    type: "likert-scale",
    dimension: "Shared Values",
    options: [
      { id: "rel_3_1", label: "Strongly Disagree", value: 1 },
      { id: "rel_3_2", label: "Disagree", value: 2 },
      { id: "rel_3_3", label: "Neutral", value: 3 },
      { id: "rel_3_4", label: "Agree", value: 4 },
      { id: "rel_3_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "rel_q4",
    title: "We actively encourage each other to pursue personal passions, hobbies, and friendships outside our partnership.",
    subtitle: "Healthy differentiation and autonomy support.",
    type: "likert-scale",
    dimension: "Mutual Growth",
    options: [
      { id: "rel_4_1", label: "Strongly Disagree", value: 1 },
      { id: "rel_4_2", label: "Disagree", value: 2 },
      { id: "rel_4_3", label: "Neutral", value: 3 },
      { id: "rel_4_4", label: "Agree", value: 4 },
      { id: "rel_4_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "rel_q5",
    title: "I feel completely safe revealing my deepest fears, insecurities, and flaws without fear of mockery or judgment.",
    subtitle: "Psychological safety and vulnerability.",
    type: "likert-scale",
    dimension: "Emotional Attunement",
    options: [
      { id: "rel_5_1", label: "Strongly Disagree", value: 1 },
      { id: "rel_5_2", label: "Disagree", value: 2 },
      { id: "rel_5_3", label: "Neutral", value: 3 },
      { id: "rel_5_4", label: "Agree", value: 4 },
      { id: "rel_5_5", label: "Strongly Agree", value: 5 },
    ],
  },

  // STAGE 2: Emotional Responsiveness & Habitual Attunement (Questions 6–10)
  {
    id: "rel_q6",
    title: "How often do you turn toward your partner when they make an emotional 'bid' for connection (a comment, touch, sigh)?",
    subtitle: "Gottman bid-responsiveness frequency.",
    type: "frequency",
    dimension: "Emotional Attunement",
    options: [
      { id: "rel_6_a", label: "Rarely — we often exist in disconnected parallel worlds", value: 1 },
      { id: "rel_6_b", label: "Sometimes when convenient", value: 2 },
      { id: "rel_6_c", label: "Consistently throughout the day", value: 4 },
      { id: "rel_6_d", label: "Almost always — we prioritize mutual attentiveness", value: 5 },
    ],
  },
  {
    id: "rel_q7",
    title: "During tense arguments, one of us shuts down completely, gives the silent treatment, or walks out without warning.",
    subtitle: "Reverse-scored stonewalling index.",
    type: "frequency",
    dimension: "Constructive Conflict",
    reversed: true,
    options: [
      { id: "rel_7_a", label: "Never or almost never", value: 1 },
      { id: "rel_7_b", label: "Rarely during extreme exhaustion", value: 2 },
      { id: "rel_7_c", label: "Occasionally during heavy arguments", value: 3 },
      { id: "rel_7_d", label: "Frequently — stonewalling is our routine pattern", value: 4 },
    ],
  },
  {
    id: "rel_q8",
    title: "When discussing long-term financial priorities (saving, spending, investing), we reach harmonious decisions without bitterness.",
    subtitle: "Financial value harmony.",
    type: "likert-scale",
    dimension: "Shared Values",
    options: [
      { id: "rel_8_1", label: "Strongly Disagree", value: 1 },
      { id: "rel_8_2", label: "Disagree", value: 2 },
      { id: "rel_8_3", label: "Neutral", value: 3 },
      { id: "rel_8_4", label: "Agree", value: 4 },
      { id: "rel_8_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "rel_q9",
    title: "We inspire each other to learn new skills, read, stay healthy, and become better versions of ourselves.",
    subtitle: "Mutual inspirational catalyst.",
    type: "likert-scale",
    dimension: "Mutual Growth",
    options: [
      { id: "rel_9_1", label: "Strongly Disagree", value: 1 },
      { id: "rel_9_2", label: "Disagree", value: 2 },
      { id: "rel_9_3", label: "Neutral", value: 3 },
      { id: "rel_9_4", label: "Agree", value: 4 },
      { id: "rel_9_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "rel_q10",
    title: "I can accurately sense when my partner is anxious, hurting, or overwhelmed before they have to say a word.",
    subtitle: "Intuitive emotional resonance.",
    type: "likert-scale",
    dimension: "Emotional Attunement",
    options: [
      { id: "rel_10_1", label: "Strongly Disagree", value: 1 },
      { id: "rel_10_2", label: "Disagree", value: 2 },
      { id: "rel_10_3", label: "Neutral", value: 3 },
      { id: "rel_10_4", label: "Agree", value: 4 },
      { id: "rel_10_5", label: "Strongly Agree", value: 5 },
    ],
  },

  // STAGE 3: Conflict Navigation & Repair Scenarios (Questions 11–15)
  {
    id: "rel_q11",
    title: "After an intense argument leaves both of you shaken, what typically happens next?",
    subtitle: "Repair attempt readiness.",
    type: "scenario",
    dimension: "Constructive Conflict",
    options: [
      { id: "rel_11_a", label: "One or both of us initiates a repair attempt within hours, offering an apology or physical warmth.", value: 5, description: "Fast repair & reconnection" },
      { id: "rel_11_b", label: "We sleep on it and talk through it calmly the next morning.", value: 4, description: "Deliberate overnight de-escalation" },
      { id: "rel_11_c", label: "We pretend nothing happened without ever talking it through.", value: 2, description: "Sweeping conflict under the rug" },
      { id: "rel_11_d", label: "The cold silence lasts for days with passive-aggressive remarks.", value: 1, description: "Protracted resentment" },
    ],
  },
  {
    id: "rel_q12",
    title: "We agree on our definitions of loyalty, integrity, personal boundaries, and fidelity.",
    subtitle: "Boundary and trust congruence.",
    type: "likert-scale",
    dimension: "Shared Values",
    options: [
      { id: "rel_12_1", label: "Strongly Disagree", value: 1 },
      { id: "rel_12_2", label: "Disagree", value: 2 },
      { id: "rel_12_3", label: "Neutral", value: 3 },
      { id: "rel_12_4", label: "Agree", value: 4 },
      { id: "rel_12_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "rel_q13",
    title: "When one of us undergoes a major personal evolution or career transition, the relationship adapts and expands.",
    subtitle: "Relational adaptability to growth.",
    type: "likert-scale",
    dimension: "Mutual Growth",
    options: [
      { id: "rel_13_1", label: "Strongly Disagree", value: 1 },
      { id: "rel_13_2", label: "Disagree", value: 2 },
      { id: "rel_13_3", label: "Neutral", value: 3 },
      { id: "rel_13_4", label: "Agree", value: 4 },
      { id: "rel_13_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "rel_q14",
    title: "I use sarcasm, eye-rolling, or contemptuous remarks during arguments with my partner.",
    subtitle: "Reverse-scored contempt indicator (Gottman's #1 relationship predictor).",
    type: "likert-scale",
    dimension: "Constructive Conflict",
    reversed: true,
    options: [
      { id: "rel_14_1", label: "Strongly Agree", value: 1 },
      { id: "rel_14_2", label: "Agree", value: 2 },
      { id: "rel_14_3", label: "Neutral", value: 3 },
      { id: "rel_14_4", label: "Disagree", value: 4 },
      { id: "rel_14_5", label: "Strongly Disagree", value: 5 },
    ],
  },
  {
    id: "rel_q15",
    title: "We have regular rituals of connection (morning coffee, shared walks, weekly date nights) that remain protected.",
    subtitle: "Connection ritual consistency.",
    type: "likert-scale",
    dimension: "Emotional Attunement",
    options: [
      { id: "rel_15_1", label: "Strongly Disagree", value: 1 },
      { id: "rel_15_2", label: "Disagree", value: 2 },
      { id: "rel_15_3", label: "Neutral", value: 3 },
      { id: "rel_15_4", label: "Agree", value: 4 },
      { id: "rel_15_5", label: "Strongly Agree", value: 5 },
    ],
  },

  // STAGE 4: Long-Term Horizons & Shared Future (Questions 16–20)
  {
    id: "rel_q16",
    title: "When we imagine our lives 10 to 20 years into the future, our visions naturally align and complement each other.",
    subtitle: "Long-term future horizon congruence.",
    type: "likert-scale",
    dimension: "Shared Values",
    options: [
      { id: "rel_16_1", label: "Strongly Disagree", value: 1 },
      { id: "rel_16_2", label: "Disagree", value: 2 },
      { id: "rel_16_3", label: "Neutral", value: 3 },
      { id: "rel_16_4", label: "Agree", value: 4 },
      { id: "rel_16_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "rel_q17",
    title: "We celebrate each other's individual triumphs without subtle feelings of envy, resentment, or competition.",
    subtitle: "Unconditional mutual advocacy.",
    type: "likert-scale",
    dimension: "Mutual Growth",
    options: [
      { id: "rel_17_1", label: "Strongly Disagree", value: 1 },
      { id: "rel_17_2", label: "Disagree", value: 2 },
      { id: "rel_17_3", label: "Neutral", value: 3 },
      { id: "rel_17_4", label: "Agree", value: 4 },
      { id: "rel_17_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "rel_q18",
    title: "When I make a mistake or hurt my partner, I take sincere ownership without excuses or defensive blame-shifting.",
    subtitle: "Accountability and humility in conflict.",
    type: "likert-scale",
    dimension: "Constructive Conflict",
    options: [
      { id: "rel_18_1", label: "Strongly Disagree", value: 1 },
      { id: "rel_18_2", label: "Disagree", value: 2 },
      { id: "rel_18_3", label: "Neutral", value: 3 },
      { id: "rel_18_4", label: "Agree", value: 4 },
      { id: "rel_18_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "rel_q19",
    title: "We have an unspoken sense of humor and playful lightness that helps us dissolve tension during challenging days.",
    subtitle: "Playfulness and relational resilience.",
    type: "likert-scale",
    dimension: "Emotional Attunement",
    options: [
      { id: "rel_19_1", label: "Strongly Disagree", value: 1 },
      { id: "rel_19_2", label: "Disagree", value: 2 },
      { id: "rel_19_3", label: "Neutral", value: 3 },
      { id: "rel_19_4", label: "Agree", value: 4 },
      { id: "rel_19_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "rel_q20",
    title: "Being in this relationship makes me feel more confident, secure, and grounded in who I truly am.",
    subtitle: "Secure attachment and flourishing self.",
    type: "likert-scale",
    dimension: "Mutual Growth",
    options: [
      { id: "rel_20_1", label: "Strongly Disagree", value: 1 },
      { id: "rel_20_2", label: "Disagree", value: 2 },
      { id: "rel_20_3", label: "Neutral", value: 3 },
      { id: "rel_20_4", label: "Agree", value: 4 },
      { id: "rel_20_5", label: "Strongly Agree", value: 5 },
    ],
  },
];
