import { AssessmentMeta, CategoryInfo } from "@/types/assessment";

export const CATEGORIES: CategoryInfo[] = [
  {
    id: "mind",
    name: "Mind",
    description: "Pattern recognition, personality, and cognitive exploration",
    iconName: "Brain",
  },
  {
    id: "wellbeing",
    name: "Wellbeing",
    description: "Stress, sleep patterns, and digital balance",
    iconName: "HeartPulse",
  },
  {
    id: "productivity",
    name: "Productivity",
    description: "Focus, time allocation, and daily momentum",
    iconName: "Zap",
  },
  {
    id: "finance",
    name: "Finance",
    description: "Money mindset, risk appetite, and spending habits",
    iconName: "Wallet",
  },
  {
    id: "career",
    name: "Career",
    description: "Workplace motivations and vocational interests",
    iconName: "Briefcase",
  },
  {
    id: "relationships",
    name: "Relationships",
    description: "Communication style and partnership dynamics",
    iconName: "Users",
  },
];

export const ASSESSMENTS_CATALOG: AssessmentMeta[] = [
  {
    id: "iq",
    slug: "iq",
    title: "Pattern Recognition & Reasoning",
    shortDescription: "Explore logical patterns, spatial problems, and analytical deduction.",
    description: "An informal cognitive exercise measuring visual pattern recognition, sequential logic, and problem-solving habits.",
    category: "mind",
    estimatedDuration: "6–8 min",
    questionCount: 20,
    featured: true,
    popular: true,
    dimensions: ["Visual Logic", "Sequence Analysis", "Spatial Deduction", "Cognitive Speed"],
    disclaimer: "This assessment provides an informal indication of problem-solving patterns. It is not an official IQ test or clinical cognitive evaluation.",
    relatedAssessments: ["learning-style", "personality", "productivity"],
  },
  {
    id: "personality",
    slug: "personality",
    title: "Core Personality Profile",
    shortDescription: "Discover your predominant traits across openness, drive, and social energy.",
    description: "Explore your natural tendencies, social preferences, and emotional equilibrium through a multi-dimensional self-reflection framework.",
    category: "mind",
    estimatedDuration: "5–7 min",
    questionCount: 20,
    featured: false,
    popular: true,
    dimensions: ["Openness", "Conscientiousness", "Social Energy", "Empathy", "Resilience"],
    disclaimer: "This assessment is for personal discovery only and does not constitute a clinical psychiatric or psychological diagnosis.",
    relatedAssessments: ["communication", "career-interest", "stress"],
  },
  {
    id: "stress",
    slug: "stress",
    title: "Daily Stress & Load Indicator",
    shortDescription: "Measure your current perceived lifestyle load and recovery balance.",
    description: "Reflect on day-to-day pressure, physical tension cues, and situational triggers to understand your current stress balance.",
    category: "wellbeing",
    estimatedDuration: "4–6 min",
    questionCount: 20,
    featured: false,
    popular: true,
    dimensions: ["Cognitive Pressure", "Physical Tension", "Emotional Load", "Recovery Margin"],
    disclaimer: "This self-assessment provides an informal indication based on your answers. It is not a clinical diagnosis for anxiety or depression.",
    relatedAssessments: ["sleep", "digital-wellbeing", "time-management"],
  },
  {
    id: "productivity",
    slug: "productivity",
    title: "Productivity & Focus Score",
    shortDescription: "Evaluate your focus depth, planning discipline, and task execution.",
    description: "Identify how effectively you plan, protect deep focus, navigate interruptions, and complete meaningful daily goals.",
    category: "productivity",
    estimatedDuration: "5–6 min",
    questionCount: 20,
    featured: true,
    popular: true,
    dimensions: ["Goal Clarity", "Distraction Control", "Execution Stamina", "System Consistency"],
    disclaimer: "Designed for personal self-improvement and workflow refinement.",
    relatedAssessments: ["time-management", "stress", "spending-habits"],
  },
  {
    id: "sleep",
    slug: "sleep",
    title: "Sleep Habits & Rest Score",
    shortDescription: "Examine your evening wind-down, sleep consistency, and daytime recovery.",
    description: "Assess your bedtime habits, environment cues, and morning alertness to pinpoint restorative rest opportunities.",
    category: "wellbeing",
    estimatedDuration: "4–5 min",
    questionCount: 20,
    featured: false,
    popular: true,
    dimensions: ["Circadian Consistency", "Evening Wind-Down", "Sleep Quality", "Morning Alertness"],
    disclaimer: "This informal evaluation does not diagnose insomnia, sleep apnea, or medical sleep disorders.",
    relatedAssessments: ["stress", "digital-wellbeing"],
  },
  {
    id: "financial-health",
    slug: "financial-health",
    title: "Financial Health & Mindset",
    shortDescription: "Assess your financial buffer, debt comfort, and future readiness.",
    description: "A constructive look at your money confidence, emergency savings security, and strategic spending habits.",
    category: "finance",
    estimatedDuration: "5–7 min",
    questionCount: 20,
    featured: true,
    popular: true,
    dimensions: ["Budget Discipline", "Safety Buffer", "Debt Management", "Future Planning"],
    disclaimer: "Provides educational insights only. This is not certified financial, investment, or legal advice.",
    relatedAssessments: ["spending-habits", "risk-tolerance"],
  },
  {
    id: "risk-tolerance",
    slug: "risk-tolerance",
    title: "Financial Risk Tolerance",
    shortDescription: "Understand your psychological comfort with volatility and uncertainty.",
    description: "Explore how you emotionally and logically respond to potential market drawdowns, career pivots, and unexpected trade-offs.",
    category: "finance",
    estimatedDuration: "4–6 min",
    questionCount: 20,
    featured: false,
    popular: false,
    dimensions: ["Loss Aversion", "Volatility Comfort", "Time Horizon", "Calculated Risk Taking"],
    disclaimer: "This questionnaire is for educational reflection and does not constitute fiduciary or investment advice.",
    relatedAssessments: ["financial-health", "spending-habits"],
  },
  {
    id: "career-interest",
    slug: "career-interest",
    title: "Career Motivations & Interests",
    shortDescription: "Uncover which work activities, environments, and goals energize you.",
    description: "Examine whether you lean toward analytical, creative, managerial, or hands-on career domains.",
    category: "career",
    estimatedDuration: "6–8 min",
    questionCount: 20,
    featured: false,
    popular: true,
    dimensions: ["Analytical", "Creative", "Leadership", "Operational", "Service"],
    disclaimer: "An informal tool for career exploration and professional reflection.",
    relatedAssessments: ["productivity", "communication", "learning-style"],
  },
  {
    id: "digital-wellbeing",
    slug: "digital-wellbeing",
    title: "Digital Wellbeing & Screen Habits",
    shortDescription: "Evaluate your relationship with notifications, social media, and screen time.",
    description: "Understand your digital boundaries, mindless scrolling tendencies, and technology-driven attention fragmentation.",
    category: "wellbeing",
    estimatedDuration: "4–5 min",
    questionCount: 20,
    featured: false,
    popular: false,
    dimensions: ["Notification Resilience", "Intentional Usage", "Bedtime Disconnect", "Focus Protection"],
    disclaimer: "An educational check-in for digital mindfulness, not a clinical screening.",
    relatedAssessments: ["stress", "sleep", "productivity"],
  },
  {
    id: "relationship",
    slug: "relationship",
    title: "Relationship Dynamics & Compatibility",
    shortDescription: "Explore emotional connection patterns, trust foundations, and conflict style.",
    description: "Examine how you give and receive support, navigate disagreements, and foster mutual understanding.",
    category: "relationships",
    estimatedDuration: "6–7 min",
    questionCount: 20,
    featured: false,
    popular: true,
    dimensions: ["Emotional Attunement", "Constructive Conflict", "Shared Values", "Mutual Growth"],
    disclaimer: "An educational self-reflection tool, not marriage or clinical relationship counseling.",
    relatedAssessments: ["communication", "personality"],
  },
  {
    id: "communication",
    slug: "communication",
    title: "Communication Style Assessment",
    shortDescription: "Identify whether your natural style is assertive, empathetic, or analytical.",
    description: "Discover how you express ideas, listen actively under pressure, and bridge differences in conversations.",
    category: "relationships",
    estimatedDuration: "5–6 min",
    questionCount: 20,
    featured: false,
    popular: false,
    dimensions: ["Directness", "Empathetic Listening", "Diplomacy", "Nonverbal Sensitivity"],
    disclaimer: "Designed for personal development and social effectiveness.",
    relatedAssessments: ["relationship", "personality", "career-interest"],
  },
  {
    id: "learning-style",
    slug: "learning-style",
    title: "Learning & Cognitive Preferences",
    shortDescription: "Find your optimal ways to absorb, synthesize, and retain new information.",
    description: "Determine whether visual models, hands-on experimentation, or structured reading accelerates your mastery.",
    category: "mind",
    estimatedDuration: "5–6 min",
    questionCount: 20,
    featured: false,
    popular: false,
    dimensions: ["Visual Synthesis", "Applied Practice", "Auditory & Dialogue", "Conceptual Frameworks"],
    disclaimer: "Educational guide for personal study habits and self-directed learning.",
    relatedAssessments: ["iq", "productivity", "career-interest"],
  },
  {
    id: "time-management",
    slug: "time-management",
    title: "Time Allocation & Pacing Score",
    shortDescription: "Discover how effectively you prioritize, estimate, and protect your hours.",
    description: "Analyze how you balance urgent versus important tasks, combat procrastination, and maintain long-term stamina.",
    category: "productivity",
    estimatedDuration: "4–6 min",
    questionCount: 20,
    featured: false,
    popular: true,
    dimensions: ["Priority Setting", "Procrastination Shield", "Time Estimation", "Buffer Discipline"],
    disclaimer: "Intended for personal efficiency and workflow awareness.",
    relatedAssessments: ["productivity", "stress"],
  },
  {
    id: "spending-habits",
    slug: "spending-habits",
    title: "Spending Habits & Impulse Control",
    shortDescription: "Understand emotional purchase triggers and value-aligned spending.",
    description: "Evaluate your shopping awareness, emotional spending cues, and intentional consumption practices.",
    category: "finance",
    estimatedDuration: "4–5 min",
    questionCount: 20,
    featured: false,
    popular: false,
    dimensions: ["Impulse Control", "Value Alignment", "Comparison Shopping", "Emotional Spending"],
    disclaimer: "Provides behavioral insights for personal budgeting awareness. Not certified financial advice.",
    relatedAssessments: ["financial-health", "risk-tolerance"],
  },
];

export function getAssessmentBySlug(slug: string): AssessmentMeta | undefined {
  return ASSESSMENTS_CATALOG.find((a) => a.slug === slug);
}

export function getAssessmentsByCategory(category: string): AssessmentMeta[] {
  return ASSESSMENTS_CATALOG.filter((a) => a.category === category);
}

export function getFeaturedAssessments(): AssessmentMeta[] {
  return ASSESSMENTS_CATALOG.filter((a) => a.featured);
}

export function getPopularAssessments(): AssessmentMeta[] {
  return ASSESSMENTS_CATALOG.filter((a) => a.popular);
}
