import { Question } from "@/types/question";

export const personalityQuestions: Question[] = [
  // STAGE 1: Openness to Experience & Intellectual Curiosity (Questions 1–4)
  {
    id: "per_q1",
    title: "I am drawn to abstract theories, unconventional concepts, and philosophical inquiry.",
    subtitle: "Intellectual exploration and cognitive novelty.",
    type: "likert-scale",
    dimension: "Openness",
    options: [
      { id: "per_1_1", label: "Strongly Disagree", value: 1 },
      { id: "per_1_2", label: "Disagree", value: 2 },
      { id: "per_1_3", label: "Neutral", value: 3 },
      { id: "per_1_4", label: "Agree", value: 4 },
      { id: "per_1_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "per_q2",
    title: "When traveling or exploring a new city, which activity most appeals to you?",
    subtitle: "Aesthetic and cultural engagement preference.",
    type: "scenario",
    dimension: "Openness",
    options: [
      { id: "per_2_a", label: "Wandering unplanned through historic alleys, art museums, and local markets.", value: 5, description: "High aesthetic curiosity" },
      { id: "per_2_b", label: "Sampling famous regional cuisine and learning the city's backstory.", value: 4, description: "Experiential exploration" },
      { id: "per_2_c", label: "Following an organized, highly structured tourist itinerary.", value: 2, description: "Conventional structured travel" },
      { id: "per_2_d", label: "Sticking strictly to familiar chain restaurants and standard hotels.", value: 1, description: "Low novelty preference" },
    ],
  },
  {
    id: "per_q3",
    title: "I prefer familiar, established routines over constant change and unpredictability.",
    subtitle: "Reverse-scored novelty preference.",
    type: "likert-scale",
    dimension: "Openness",
    reversed: true,
    options: [
      { id: "per_3_1", label: "Strongly Agree", value: 1 },
      { id: "per_3_2", label: "Agree", value: 2 },
      { id: "per_3_3", label: "Neutral", value: 3 },
      { id: "per_3_4", label: "Disagree", value: 4 },
      { id: "per_3_5", label: "Strongly Disagree", value: 5 },
    ],
  },
  {
    id: "per_q4",
    title: "I often experience vivid emotional resonance when listening to complex music, viewing art, or observing nature.",
    subtitle: "Aesthetic sensitivity and depth.",
    type: "likert-scale",
    dimension: "Openness",
    options: [
      { id: "per_4_1", label: "Strongly Disagree", value: 1 },
      { id: "per_4_2", label: "Disagree", value: 2 },
      { id: "per_4_3", label: "Neutral", value: 3 },
      { id: "per_4_4", label: "Agree", value: 4 },
      { id: "per_4_5", label: "Strongly Agree", value: 5 },
    ],
  },

  // STAGE 2: Conscientiousness & Operational Discipline (Questions 5–8)
  {
    id: "per_q5",
    title: "I keep my physical and digital work environments organized, deliberate, and tidy.",
    subtitle: "Orderliness and spatial structure.",
    type: "likert-scale",
    dimension: "Conscientiousness",
    options: [
      { id: "per_5_1", label: "Strongly Disagree", value: 1 },
      { id: "per_5_2", label: "Disagree", value: 2 },
      { id: "per_5_3", label: "Neutral", value: 3 },
      { id: "per_5_4", label: "Agree", value: 4 },
      { id: "per_5_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "per_q6",
    title: "When assigned a project with a deadline three weeks away:",
    subtitle: "Task initiation and pacing tendency.",
    type: "scenario",
    dimension: "Conscientiousness",
    options: [
      { id: "per_6_a", label: "I break it into milestones immediately and complete a draft well in advance.", value: 5, description: "Proactive milestone pacing" },
      { id: "per_6_b", label: "I map a steady plan and execute reliably day by day.", value: 4, description: "Consistent structured delivery" },
      { id: "per_6_c", label: "I delay initiation until the final week when pressure mounts.", value: 2, description: "Pressure-dependent execution" },
      { id: "per_6_d", label: "I pull an all-nighter the night before the deadline.", value: 1, description: "Chronic eleventh-hour scrambling" },
    ],
  },
  {
    id: "per_q7",
    title: "I follow through on commitments and promises, even when personal motivation wanes.",
    subtitle: "Reliability and duty orientation.",
    type: "likert-scale",
    dimension: "Conscientiousness",
    options: [
      { id: "per_7_1", label: "Strongly Disagree", value: 1 },
      { id: "per_7_2", label: "Disagree", value: 2 },
      { id: "per_7_3", label: "Neutral", value: 3 },
      { id: "per_7_4", label: "Agree", value: 4 },
      { id: "per_7_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "per_q8",
    title: "I am frequently careless with minor details or misplace personal belongings.",
    subtitle: "Reverse-scored precision and thoroughness.",
    type: "likert-scale",
    dimension: "Conscientiousness",
    reversed: true,
    options: [
      { id: "per_8_1", label: "Strongly Agree", value: 1 },
      { id: "per_8_2", label: "Agree", value: 2 },
      { id: "per_8_3", label: "Neutral", value: 3 },
      { id: "per_8_4", label: "Disagree", value: 4 },
      { id: "per_8_5", label: "Strongly Disagree", value: 5 },
    ],
  },

  // STAGE 3: Social Energy & Assertiveness (Questions 9–12)
  {
    id: "per_q9",
    title: "After spending an entire weekend alone in solitary activities, how do you feel?",
    subtitle: "Internal battery recharge dynamic (Extraversion vs Introversion).",
    type: "single-choice",
    dimension: "Social Energy",
    options: [
      { id: "per_9_a", label: "Restored, deeply grounded, and at peace (Introvert recharge)", value: 2 },
      { id: "per_9_b", label: "Balanced, but looking forward to seeing friends soon", value: 3 },
      { id: "per_9_c", label: "A bit restless; I miss group energy and social interaction", value: 4 },
      { id: "per_9_d", label: "Stir-crazy and starved for social stimulation (High Extraversion)", value: 5 },
    ],
  },
  {
    id: "per_q10",
    title: "I easily take the lead in group discussions and express my perspectives without hesitation.",
    subtitle: "Social assertiveness and conversational leadership.",
    type: "likert-scale",
    dimension: "Social Energy",
    options: [
      { id: "per_10_1", label: "Strongly Disagree", value: 1 },
      { id: "per_10_2", label: "Disagree", value: 2 },
      { id: "per_10_3", label: "Neutral", value: 3 },
      { id: "per_10_4", label: "Agree", value: 4 },
      { id: "per_10_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "per_q11",
    title: "At a gathering where you only know the host, which best describes your behavior?",
    subtitle: "Social initiative in novel environments.",
    type: "scenario",
    dimension: "Social Energy",
    options: [
      { id: "per_11_a", label: "I proactively introduce myself to multiple groups and make new connections.", value: 5, description: "Outgoing exploratory extraversion" },
      { id: "per_11_b", label: "I find one or two individuals for engaging, focused one-on-one conversation.", value: 3, description: "Selective depth orientation" },
      { id: "per_11_c", label: "I stay near the host or food area, waiting for others to approach me.", value: 2, description: "Reserved social posture" },
      { id: "per_11_d", label: "I feel intense social exhaustion and leave as politely and quickly as possible.", value: 1, description: "High solitary preference" },
    ],
  },
  {
    id: "per_q12",
    title: "I enjoy being the focal center of attention in group environments.",
    subtitle: "Exhibition and social spotlight affinity.",
    type: "likert-scale",
    dimension: "Social Energy",
    options: [
      { id: "per_12_1", label: "Strongly Disagree", value: 1 },
      { id: "per_12_2", label: "Disagree", value: 2 },
      { id: "per_12_3", label: "Neutral", value: 3 },
      { id: "per_12_4", label: "Agree", value: 4 },
      { id: "per_12_5", label: "Strongly Agree", value: 5 },
    ],
  },

  // STAGE 4: Empathy & Relational Attunement (Questions 13–16)
  {
    id: "per_q13",
    title: "I intuitively sense what others are feeling before they explicitly verbalize it.",
    subtitle: "Emotional attunement and perspective taking.",
    type: "likert-scale",
    dimension: "Empathy",
    options: [
      { id: "per_13_1", label: "Strongly Disagree", value: 1 },
      { id: "per_13_2", label: "Disagree", value: 2 },
      { id: "per_13_3", label: "Neutral", value: 3 },
      { id: "per_13_4", label: "Agree", value: 4 },
      { id: "per_13_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "per_q14",
    title: "When a colleague or friend makes an unintentional error that affects your schedule:",
    subtitle: "Compassion vs critical reaction in interpersonal friction.",
    type: "scenario",
    dimension: "Empathy",
    options: [
      { id: "per_14_a", label: "I show warmth, reassure them, and collaborate on a painless fix.", value: 5, description: "Empathetic collaborative response" },
      { id: "per_14_b", label: "I calmly accept the delay and adjust my plans without irritation.", value: 4, description: "Equanimous acceptance" },
      { id: "per_14_c", label: "I point out their mistake with blunt, direct frustration.", value: 2, description: "Low emotional filtering" },
      { id: "per_14_d", label: "I harbor silent resentment and mentally catalog their carelessness.", value: 1, description: "Critical grievance retention" },
    ],
  },
  {
    id: "per_q15",
    title: "I am willing to compromise my immediate personal convenience to support someone in need.",
    subtitle: "Altruistic prosocial behavior.",
    type: "likert-scale",
    dimension: "Empathy",
    options: [
      { id: "per_15_1", label: "Strongly Disagree", value: 1 },
      { id: "per_15_2", label: "Disagree", value: 2 },
      { id: "per_15_3", label: "Neutral", value: 3 },
      { id: "per_15_4", label: "Agree", value: 4 },
      { id: "per_15_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "per_q16",
    title: "I tend to judge people harshly or feel indifferent toward others' misfortunes.",
    subtitle: "Reverse-scored empathy indicator.",
    type: "likert-scale",
    dimension: "Empathy",
    reversed: true,
    options: [
      { id: "per_16_1", label: "Strongly Agree", value: 1 },
      { id: "per_16_2", label: "Agree", value: 2 },
      { id: "per_16_3", label: "Neutral", value: 3 },
      { id: "per_16_4", label: "Disagree", value: 4 },
      { id: "per_16_5", label: "Strongly Disagree", value: 5 },
    ],
  },

  // STAGE 5: Emotional Resilience & Composure (Questions 17–20)
  {
    id: "per_q17",
    title: "When facing major unexpected disruptions, I regain emotional composure quickly.",
    subtitle: "Psychological bouncing back and equilibrium recovery.",
    type: "likert-scale",
    dimension: "Resilience",
    options: [
      { id: "per_17_1", label: "Strongly Disagree", value: 1 },
      { id: "per_17_2", label: "Disagree", value: 2 },
      { id: "per_17_3", label: "Neutral", value: 3 },
      { id: "per_17_4", label: "Agree", value: 4 },
      { id: "per_17_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "per_q18",
    title: "I frequently worry about things that I cannot directly influence or control.",
    subtitle: "Reverse-scored chronic anxiety and rumination.",
    type: "likert-scale",
    dimension: "Resilience",
    reversed: true,
    options: [
      { id: "per_18_1", label: "Strongly Agree", value: 1 },
      { id: "per_18_2", label: "Agree", value: 2 },
      { id: "per_18_3", label: "Neutral", value: 3 },
      { id: "per_18_4", label: "Disagree", value: 4 },
      { id: "per_18_5", label: "Strongly Disagree", value: 5 },
    ],
  },
  {
    id: "per_q19",
    title: "Scenario: A high-stakes venture fails despite your diligent preparation. What is your internal reaction?",
    subtitle: "Attributional style and fortitude under failure.",
    type: "scenario",
    dimension: "Resilience",
    options: [
      { id: "per_19_a", label: "I conduct an objective post-mortem, extract lessons, and begin the next iteration.", value: 5, description: "Growth-oriented fortitude" },
      { id: "per_19_b", label: "I feel disappointed for a day or two, then regroup with renewed resolve.", value: 4, description: "Healthy adaptive recovery" },
      { id: "per_19_c", label: "I experience intense self-blame and doubt my competence for months.", value: 2, description: "Rumination and self-criticism" },
      { id: "per_19_d", label: "I abandon similar efforts entirely and adopt defensive pessimism.", value: 1, description: "Learned helplessness reaction" },
    ],
  },
  {
    id: "per_q20",
    title: "My mood remains generally even-keeled, stable, and optimistic across seasonal changes.",
    subtitle: "Affective stability baseline.",
    type: "likert-scale",
    dimension: "Resilience",
    options: [
      { id: "per_20_1", label: "Strongly Disagree", value: 1 },
      { id: "per_20_2", label: "Disagree", value: 2 },
      { id: "per_20_3", label: "Neutral", value: 3 },
      { id: "per_20_4", label: "Agree", value: 4 },
      { id: "per_20_5", label: "Strongly Agree", value: 5 },
    ],
  },
];
