import { Question } from "@/types/question";

export const learningStyleQuestions: Question[] = [
  // STAGE 1: Visual Synthesis & Spatial Models (Questions 1–5)
  {
    id: "lrn_q1",
    title: "When learning how a complex system works (e.g. an engine, a software architecture), which resource helps you absorb it fastest?",
    subtitle: "Primary informational format preference.",
    type: "single-choice",
    dimension: "Visual Synthesis",
    options: [
      { id: "lrn_1_a", label: "A color-coded visual diagram, flowchart, or schematic map", value: 5 },
      { id: "lrn_1_b", label: "Tinkering directly with a working interactive prototype", value: 3 },
      { id: "lrn_1_c", label: "An in-depth podcast or conversational breakdown with an expert", value: 2 },
      { id: "lrn_1_d", label: "A dense theoretical treatise outlining underlying axioms", value: 3 },
    ],
  },
  {
    id: "lrn_q2",
    title: "I naturally sketch mind maps, boxes, or spatial doodles to organize my thoughts when solving problems.",
    subtitle: "Spatial externalization propensity.",
    type: "likert-scale",
    dimension: "Visual Synthesis",
    options: [
      { id: "lrn_2_1", label: "Strongly Disagree", value: 1 },
      { id: "lrn_2_2", label: "Disagree", value: 2 },
      { id: "lrn_2_3", label: "Neutral", value: 3 },
      { id: "lrn_2_4", label: "Agree", value: 4 },
      { id: "lrn_2_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "lrn_q3",
    title: "I recall information more vividly by picturing where it was located on a page or slide rather than remembering the exact words spoken.",
    subtitle: "Eidetic spatial memory retention.",
    type: "likert-scale",
    dimension: "Visual Synthesis",
    options: [
      { id: "lrn_3_1", label: "Strongly Disagree", value: 1 },
      { id: "lrn_3_2", label: "Disagree", value: 2 },
      { id: "lrn_3_3", label: "Neutral", value: 3 },
      { id: "lrn_3_4", label: "Agree", value: 4 },
      { id: "lrn_3_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "lrn_q4",
    title: "Scenario: You buy complex modular furniture that requires multi-step assembly. What is your process?",
    subtitle: "Visual diagram vs procedural instruction processing.",
    type: "scenario",
    dimension: "Visual Synthesis",
    options: [
      { id: "lrn_4_a", label: "I scan the illustrated exploded diagrams; visual layouts make the logic obvious.", value: 5, description: "Pure visual spatial mapping" },
      { id: "lrn_4_b", label: "I start putting pieces together by hand immediately, referencing pictures only if stuck.", value: 3, description: "Applied kinesthetic trial" },
      { id: "lrn_4_c", label: "I watch a 5-minute video tutorial of someone assembling it step by step.", value: 4, description: "Dynamic audiovisual demonstration" },
      { id: "lrn_4_d", label: "I carefully read every numbered textual instruction line by line.", value: 2, description: "Sequential verbal processing" },
    ],
  },
  {
    id: "lrn_q5",
    title: "I struggle to retain dense verbal lectures if there are no visual slides or whiteboard diagrams.",
    subtitle: "Visual dependency in verbal environments.",
    type: "likert-scale",
    dimension: "Visual Synthesis",
    options: [
      { id: "lrn_5_1", label: "Strongly Disagree", value: 1 },
      { id: "lrn_5_2", label: "Disagree", value: 2 },
      { id: "lrn_5_3", label: "Neutral", value: 3 },
      { id: "lrn_5_4", label: "Agree", value: 4 },
      { id: "lrn_5_5", label: "Strongly Agree", value: 5 },
    ],
  },

  // STAGE 2: Applied Practice & Kinesthetic Learning (Questions 6–10)
  {
    id: "lrn_q6",
    title: "How quickly do you prefer to transition from reading theory to touching hands-on implementation?",
    subtitle: "Experiential cycle velocity.",
    type: "single-choice",
    dimension: "Applied Practice",
    options: [
      { id: "lrn_6_a", label: "Immediately — I learn by breaking and building things directly", value: 5 },
      { id: "lrn_6_b", label: "After a quick 10-minute overview of basics", value: 4 },
      { id: "lrn_6_c", label: "Only after thoroughly reading the full documentation", value: 2 },
      { id: "lrn_6_d", label: "I prefer understanding abstract principles without physical execution", value: 1 },
    ],
  },
  {
    id: "lrn_q7",
    title: "I remember concepts best when I actively build, code, write, or physically demonstrate them.",
    subtitle: "Kinesthetic encoding and motor reinforcement.",
    type: "likert-scale",
    dimension: "Applied Practice",
    options: [
      { id: "lrn_7_1", label: "Strongly Disagree", value: 1 },
      { id: "lrn_7_2", label: "Disagree", value: 2 },
      { id: "lrn_7_3", label: "Neutral", value: 3 },
      { id: "lrn_7_4", label: "Agree", value: 4 },
      { id: "lrn_7_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "lrn_q8",
    title: "Scenario: You are adopting a brand new professional software tool. What is your instinctive onboarding method?",
    subtitle: "Exploratory tinkering vs formal training.",
    type: "scenario",
    dimension: "Applied Practice",
    options: [
      { id: "lrn_8_a", label: "I dive in, click buttons, test edge cases, and discover features organically.", value: 5, description: "Active experiential exploration" },
      { id: "lrn_8_b", label: "I create a sandbox test project and build a real prototype immediately.", value: 5, description: "Project-based applied learning" },
      { id: "lrn_8_c", label: "I take a comprehensive 3-hour video course before touching the interface.", value: 2, description: "Passive observational learning" },
      { id: "lrn_8_d", label: "I ask a colleague to share their screen and walk me through their workflow.", value: 3, description: "Social apprenticeship" },
    ],
  },
  {
    id: "lrn_q9",
    title: "I become restless and disengaged when required to sit passively listening for more than 40 minutes.",
    subtitle: "Active engagement necessity.",
    type: "likert-scale",
    dimension: "Applied Practice",
    options: [
      { id: "lrn_9_1", label: "Strongly Disagree", value: 1 },
      { id: "lrn_9_2", label: "Disagree", value: 2 },
      { id: "lrn_9_3", label: "Neutral", value: 3 },
      { id: "lrn_9_4", label: "Agree", value: 4 },
      { id: "lrn_9_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "lrn_q10",
    title: "Trial-and-error experimentation teaches me more than reading pristine case studies.",
    subtitle: "Iterative feedback preference.",
    type: "likert-scale",
    dimension: "Applied Practice",
    options: [
      { id: "lrn_10_1", label: "Strongly Disagree", value: 1 },
      { id: "lrn_10_2", label: "Disagree", value: 2 },
      { id: "lrn_10_3", label: "Neutral", value: 3 },
      { id: "lrn_10_4", label: "Agree", value: 4 },
      { id: "lrn_10_5", label: "Strongly Agree", value: 5 },
    ],
  },

  // STAGE 3: Auditory & Dialogue (Questions 11–15)
  {
    id: "lrn_q11",
    title: "How effective is explaining a difficult concept out loud to another person (or rubber duck) in crystallizing your understanding?",
    subtitle: "Feynman technique auditory verbalization.",
    type: "single-choice",
    dimension: "Auditory & Dialogue",
    options: [
      { id: "lrn_11_a", label: "Transformative — hearing myself articulate it exposes all hidden blindspots", value: 5 },
      { id: "lrn_11_b", label: "Very helpful for polishing logic", value: 4 },
      { id: "lrn_11_c", label: "Slightly helpful, but silent writing works better for me", value: 2 },
      { id: "lrn_11_d", label: "Unhelpful — I think purely in silent non-verbal structures", value: 1 },
    ],
  },
  {
    id: "lrn_q12",
    title: "I enjoy educational podcasts, audiobooks, and debate panels while commuting or exercising.",
    subtitle: "Auditory knowledge acquisition bandwidth.",
    type: "likert-scale",
    dimension: "Auditory & Dialogue",
    options: [
      { id: "lrn_12_1", label: "Strongly Disagree", value: 1 },
      { id: "lrn_12_2", label: "Disagree", value: 2 },
      { id: "lrn_12_3", label: "Neutral", value: 3 },
      { id: "lrn_12_4", label: "Agree", value: 4 },
      { id: "lrn_12_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "lrn_q13",
    title: "Scenario: You are struggling with a confusing conceptual paradox in your studies. What breaks the logjam?",
    subtitle: "Dialogue and conversational synthesis.",
    type: "scenario",
    dimension: "Auditory & Dialogue",
    options: [
      { id: "lrn_13_a", label: "A vigorous 20-minute discussion bouncing ideas back and forth with a mentor.", value: 5, description: "Socratic dialectic clarity" },
      { id: "lrn_13_b", label: "Listening to a debate podcast exploring both perspectives.", value: 4, description: "Auditory multi-perspective absorption" },
      { id: "lrn_13_c", label: "Solitary diagramming and sketching the matrix on paper.", value: 2, description: "Visual solitary deconstruction" },
      { id: "lrn_13_d", label: "Building a simulation to see which premise yields an error.", value: 3, description: "Applied empirical test" },
    ],
  },
  {
    id: "lrn_q14",
    title: "I can accurately recall spoken quotes, tone inflections, and auditory nuances from conversations weeks later.",
    subtitle: "Auditory acoustic memory acuity.",
    type: "likert-scale",
    dimension: "Auditory & Dialogue",
    options: [
      { id: "lrn_14_1", label: "Strongly Disagree", value: 1 },
      { id: "lrn_14_2", label: "Disagree", value: 2 },
      { id: "lrn_14_3", label: "Neutral", value: 3 },
      { id: "lrn_14_4", label: "Agree", value: 4 },
      { id: "lrn_14_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "lrn_q15",
    title: "I frequently talk out loud to myself when reasoning through difficult mathematical or logical problems.",
    subtitle: "Auditory self-scaffolding.",
    type: "likert-scale",
    dimension: "Auditory & Dialogue",
    options: [
      { id: "lrn_15_1", label: "Strongly Disagree", value: 1 },
      { id: "lrn_15_2", label: "Disagree", value: 2 },
      { id: "lrn_15_3", label: "Neutral", value: 3 },
      { id: "lrn_15_4", label: "Agree", value: 4 },
      { id: "lrn_15_5", label: "Strongly Agree", value: 5 },
    ],
  },

  // STAGE 4: Conceptual Frameworks & First Principles (Questions 16–20)
  {
    id: "lrn_q16",
    title: "Before learning practical steps, how essential is it for you to understand the underlying 'why' and foundational theory?",
    subtitle: "First principles deductive orientation.",
    type: "single-choice",
    dimension: "Conceptual Frameworks",
    options: [
      { id: "lrn_16_a", label: "Mandatory — practical steps feel hollow unless anchored in deep first principles", value: 5 },
      { id: "lrn_16_b", label: "Helpful, but I can execute based on practical rules first", value: 3 },
      { id: "lrn_16_c", label: "Secondary — I care primarily about whether it works in practice", value: 2 },
      { id: "lrn_16_d", label: "Irrelevant — give me the cookbook recipe and skip the theory", value: 1 },
    ],
  },
  {
    id: "lrn_q17",
    title: "I naturally connect ideas across completely disparate domains (e.g. biology concepts applied to software architecture).",
    subtitle: "Interdisciplinary conceptual synthesis.",
    type: "likert-scale",
    dimension: "Conceptual Frameworks",
    options: [
      { id: "lrn_17_1", label: "Strongly Disagree", value: 1 },
      { id: "lrn_17_2", label: "Disagree", value: 2 },
      { id: "lrn_17_3", label: "Neutral", value: 3 },
      { id: "lrn_17_4", label: "Agree", value: 4 },
      { id: "lrn_17_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "lrn_q18",
    title: "Scenario: You are presented with a massive collection of isolated facts and case examples. What is your immediate impulse?",
    subtitle: "Inductive abstraction and model formation.",
    type: "scenario",
    dimension: "Conceptual Frameworks",
    options: [
      { id: "lrn_18_a", label: "I synthesize an overarching mental model that unifies all examples under one rule.", value: 5, description: "Systemic conceptual modeling" },
      { id: "lrn_18_b", label: "I categorize them into a neat visual matrix or structured hierarchy.", value: 4, description: "Structured visual taxonomizing" },
      { id: "lrn_18_c", label: "I memorize the most practical 3 examples and ignore the rest.", value: 2, description: "Pragmatic heuristic filtering" },
      { id: "lrn_18_d", label: "I feel overwhelmed by data overload and tune out.", value: 1, description: "Cognitive overload surrender" },
    ],
  },
  {
    id: "lrn_q19",
    title: "I enjoy reading foundational books, academic papers, and dense theoretical frameworks.",
    subtitle: "Abstract conceptual literature affinity.",
    type: "likert-scale",
    dimension: "Conceptual Frameworks",
    options: [
      { id: "lrn_19_1", label: "Strongly Disagree", value: 1 },
      { id: "lrn_19_2", label: "Disagree", value: 2 },
      { id: "lrn_19_3", label: "Neutral", value: 3 },
      { id: "lrn_19_4", label: "Agree", value: 4 },
      { id: "lrn_19_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "lrn_q20",
    title: "Overall, true mastery to me means having an intuitive mental model that can predict outcomes from first principles.",
    subtitle: "Epistemological definition of understanding.",
    type: "likert-scale",
    dimension: "Conceptual Frameworks",
    options: [
      { id: "lrn_20_1", label: "Strongly Disagree", value: 1 },
      { id: "lrn_20_2", label: "Disagree", value: 2 },
      { id: "lrn_20_3", label: "Neutral", value: 3 },
      { id: "lrn_20_4", label: "Agree", value: 4 },
      { id: "lrn_20_5", label: "Strongly Agree", value: 5 },
    ],
  },
];
