import { Question } from "@/types/question";

export const riskToleranceQuestions: Question[] = [
  // STAGE 1: Loss Aversion & Kahneman-Tversky Dynamics (Questions 1–5)
  {
    id: "rsk_q1",
    title: "Scenario: You are offered a coin flip gamble: 50% chance to win $1,000, 50% chance to lose $500. Do you accept?",
    subtitle: "Classic behavioral economics prospect theory benchmark.",
    type: "scenario",
    dimension: "Loss Aversion",
    options: [
      { id: "rsk_1_a", label: "Yes, definitely — positive expected value of +$250 makes this an attractive mathematical bet.", value: 5, description: "Rational expected value orientation" },
      { id: "rsk_1_b", label: "Yes, provided the $500 loss would not jeopardize my essential bills.", value: 4, description: "Controlled risk tolerance" },
      { id: "rsk_1_c", label: "Hesitant — the emotional pain of losing $500 outweighs winning $1,000.", value: 2, description: "Loss aversion asymmetry" },
      { id: "rsk_1_d", label: "No, absolutely not — I avoid all downside risk whenever possible.", value: 1, description: "High loss aversion" },
    ],
  },
  {
    id: "rsk_q2",
    title: "I feel intense anxiety and regret when an investment temporarily drops in value, even if I know pullbacks are normal.",
    subtitle: "Reverse-scored emotional paper loss sensitivity.",
    type: "likert-scale",
    dimension: "Loss Aversion",
    reversed: true,
    options: [
      { id: "rsk_2_1", label: "Strongly Agree", value: 1 },
      { id: "rsk_2_2", label: "Agree", value: 2 },
      { id: "rsk_2_3", label: "Neutral", value: 3 },
      { id: "rsk_2_4", label: "Disagree", value: 4 },
      { id: "rsk_2_5", label: "Strongly Disagree", value: 5 },
    ],
  },
  {
    id: "rsk_q3",
    title: "In financial decisions, is your primary subconscious goal avoiding loss or maximizing long-term upside?",
    subtitle: "Promotion vs prevention focus in capital allocation.",
    type: "single-choice",
    dimension: "Loss Aversion",
    options: [
      { id: "rsk_3_a", label: "Aggressive wealth compounding — volatility is the necessary price of high returns", value: 5 },
      { id: "rsk_3_b", label: "Balanced growth — striving for solid returns with reasonable downside bounds", value: 4 },
      { id: "rsk_3_c", label: "Capital preservation first — moderate returns only if capital is safe", value: 2 },
      { id: "rsk_3_d", label: "Absolute safety — guarantee my principal even if returns lag inflation", value: 1 },
    ],
  },
  {
    id: "rsk_q4",
    title: "I can look at an unrealized paper loss of 20% in my retirement account without losing sleep.",
    subtitle: "Affective resilience during market downturns.",
    type: "likert-scale",
    dimension: "Loss Aversion",
    options: [
      { id: "rsk_4_1", label: "Strongly Disagree", value: 1 },
      { id: "rsk_4_2", label: "Disagree", value: 2 },
      { id: "rsk_4_3", label: "Neutral", value: 3 },
      { id: "rsk_4_4", label: "Agree", value: 4 },
      { id: "rsk_4_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "rsk_q5",
    title: "How frequently do you check your investment portfolio balances during turbulent financial news cycles?",
    subtitle: "Myopic loss aversion monitoring frequency.",
    type: "frequency",
    dimension: "Loss Aversion",
    reversed: true,
    options: [
      { id: "rsk_5_a", label: "Never or once a quarter — I deliberately ignore short-term headlines", value: 1 },
      { id: "rsk_5_b", label: "Once a month to rebalance", value: 2 },
      { id: "rsk_5_c", label: "Several times a week", value: 3 },
      { id: "rsk_5_d", label: "Multiple times a day with high stress", value: 4 },
    ],
  },

  // STAGE 2: Volatility Comfort & Market Drawdowns (Questions 6–10)
  {
    id: "rsk_q6",
    title: "Imagine you invest $20,000 in a diversified index fund. Over the next year, the stock market crashes and your balance drops to $14,000 (-30%). What do you do?",
    subtitle: "Empirical drawdown behavioral response.",
    type: "scenario",
    dimension: "Volatility Comfort",
    options: [
      { id: "rsk_6_a", label: "I aggressively buy more shares while equities are on historical discount.", value: 5, description: "Contrarian value accumulation" },
      { id: "rsk_6_b", label: "I continue my regular scheduled automatic monthly contributions and do nothing.", value: 4, description: "Disciplined dollar-cost averaging" },
      { id: "rsk_6_c", label: "I stop monthly contributions and wait until markets show recovery signs.", value: 2, description: "Risk-off freeze" },
      { id: "rsk_6_d", label: "I sell all holdings immediately to prevent further bleeding and hold cash.", value: 1, description: "Panic selling capitulation" },
    ],
  },
  {
    id: "rsk_q7",
    title: "I understand that market volatility is not risk itself, but the price paid for long-term equity premiums.",
    subtitle: "Theoretical understanding of market drawdowns.",
    type: "likert-scale",
    dimension: "Volatility Comfort",
    options: [
      { id: "rsk_7_1", label: "Strongly Disagree", value: 1 },
      { id: "rsk_7_2", label: "Disagree", value: 2 },
      { id: "rsk_7_3", label: "Neutral", value: 3 },
      { id: "rsk_7_4", label: "Agree", value: 4 },
      { id: "rsk_7_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "rsk_q8",
    title: "Which hypothetical investment portfolio would you be most comfortable holding over the next 5 years?",
    subtitle: "Risk-return trade-off frontier selection.",
    type: "single-choice",
    dimension: "Volatility Comfort",
    options: [
      { id: "rsk_8_a", label: "Aggressive: Best year +35%, Worst year -22%, Average return ~10%", value: 5 },
      { id: "rsk_8_b", label: "Moderate Growth: Best year +20%, Worst year -12%, Average return ~7.5%", value: 4 },
      { id: "rsk_8_c", label: "Conservative: Best year +10%, Worst year -4%, Average return ~5%", value: 2 },
      { id: "rsk_8_d", label: "Ultra-Safe: Best year +3%, Worst year 0%, Average return ~2.5%", value: 1 },
    ],
  },
  {
    id: "rsk_q9",
    title: "Economic headlines forecasting an impending recession cause me to question my investment strategy.",
    subtitle: "Reverse-scored macroeconomic anxiety vulnerability.",
    type: "likert-scale",
    dimension: "Volatility Comfort",
    reversed: true,
    options: [
      { id: "rsk_9_1", label: "Strongly Agree", value: 1 },
      { id: "rsk_9_2", label: "Agree", value: 2 },
      { id: "rsk_9_3", label: "Neutral", value: 3 },
      { id: "rsk_9_4", label: "Disagree", value: 4 },
      { id: "rsk_9_5", label: "Strongly Disagree", value: 5 },
    ],
  },
  {
    id: "rsk_q10",
    title: "I am comfortable holding asset classes that fluctuate wildly day to day if the multi-year trajectory is positive.",
    subtitle: "High volatility tolerance.",
    type: "likert-scale",
    dimension: "Volatility Comfort",
    options: [
      { id: "rsk_10_1", label: "Strongly Disagree", value: 1 },
      { id: "rsk_10_2", label: "Disagree", value: 2 },
      { id: "rsk_10_3", label: "Neutral", value: 3 },
      { id: "rsk_10_4", label: "Agree", value: 4 },
      { id: "rsk_10_5", label: "Strongly Agree", value: 5 },
    ],
  },

  // STAGE 3: Time Horizon & Liquidity Architecture (Questions 11–15)
  {
    id: "rsk_q11",
    title: "What is your primary investment time horizon before you need to begin withdrawing significant principal?",
    subtitle: "Duration capacity for absorbing market cycles.",
    type: "single-choice",
    dimension: "Time Horizon",
    options: [
      { id: "rsk_11_a", label: "15+ years (decades of compounding runway)", value: 5 },
      { id: "rsk_11_b", label: "7 to 15 years", value: 4 },
      { id: "rsk_11_c", label: "3 to 6 years", value: 2 },
      { id: "rsk_11_d", label: "Under 3 years — capital is needed in the near term", value: 1 },
    ],
  },
  {
    id: "rsk_q12",
    title: "I keep sufficient cash set aside for all major upcoming purchases (home, car, wedding) so I never have to liquidate stocks during a downturn.",
    subtitle: "Asset-liability duration matching.",
    type: "likert-scale",
    dimension: "Time Horizon",
    options: [
      { id: "rsk_12_1", label: "Strongly Disagree", value: 1 },
      { id: "rsk_12_2", label: "Disagree", value: 2 },
      { id: "rsk_12_3", label: "Neutral", value: 3 },
      { id: "rsk_12_4", label: "Agree", value: 4 },
      { id: "rsk_12_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "rsk_q13",
    title: "I think about financial returns in terms of decades rather than quarters or single years.",
    subtitle: "Long-horizon compounding mindset.",
    type: "likert-scale",
    dimension: "Time Horizon",
    options: [
      { id: "rsk_13_1", label: "Strongly Disagree", value: 1 },
      { id: "rsk_13_2", label: "Disagree", value: 2 },
      { id: "rsk_13_3", label: "Neutral", value: 3 },
      { id: "rsk_13_4", label: "Agree", value: 4 },
      { id: "rsk_13_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "rsk_q14",
    title: "How often do you feel pressured to liquidate long-term investments to cover short-term living cash shortfalls?",
    subtitle: "Reverse-scored forced selling vulnerability.",
    type: "frequency",
    dimension: "Time Horizon",
    reversed: true,
    options: [
      { id: "rsk_14_a", label: "Never", value: 1 },
      { id: "rsk_14_b", label: "Rarely (once in several years)", value: 2 },
      { id: "rsk_14_c", label: "Occasionally (annually)", value: 3 },
      { id: "rsk_14_d", label: "Frequently multiple times per year", value: 4 },
    ],
  },
  {
    id: "rsk_q15",
    title: "A long investment horizon gives me the strategic freedom to tolerate severe short-term dips.",
    subtitle: "Horizon-enabled risk capacity.",
    type: "likert-scale",
    dimension: "Time Horizon",
    options: [
      { id: "rsk_15_1", label: "Strongly Disagree", value: 1 },
      { id: "rsk_15_2", label: "Disagree", value: 2 },
      { id: "rsk_15_3", label: "Neutral", value: 3 },
      { id: "rsk_15_4", label: "Agree", value: 4 },
      { id: "rsk_15_5", label: "Strongly Agree", value: 5 },
    ],
  },

  // STAGE 4: Calculated Risk Taking & Opportunity Analysis (Questions 16–20)
  {
    id: "rsk_q16",
    title: "When evaluating an asymmetric opportunity (e.g. startup equity, career pivot, novel venture), which best describes your mindset?",
    subtitle: "Asymmetric upside exploration.",
    type: "scenario",
    dimension: "Calculated Risk Taking",
    options: [
      { id: "rsk_16_a", label: "I analyze the capped downside against uncapped upside; if favorable, I lean into it.", value: 5, description: "Calculated asymmetric risk taker" },
      { id: "rsk_16_b", label: "I consider it carefully with a small, testable allocation of my capital or time.", value: 4, description: "Prudent exploratory risk" },
      { id: "rsk_16_c", label: "I prefer established, traditional paths with predictable incremental gains.", value: 2, description: "Conventional low-risk preference" },
      { id: "rsk_16_d", label: "Any risk of failure makes me uncomfortable regardless of potential reward.", value: 1, description: "Absolute risk avoidance" },
    ],
  },
  {
    id: "rsk_q17",
    title: "I am comfortable allocating 5–10% of my total investable assets into high-risk, high-reward ventures.",
    subtitle: "Barbell portfolio speculative allocation.",
    type: "likert-scale",
    dimension: "Calculated Risk Taking",
    options: [
      { id: "rsk_17_1", label: "Strongly Disagree", value: 1 },
      { id: "rsk_17_2", label: "Disagree", value: 2 },
      { id: "rsk_17_3", label: "Neutral", value: 3 },
      { id: "rsk_17_4", label: "Agree", value: 4 },
      { id: "rsk_17_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "rsk_q18",
    title: "I have taken deliberate career risks (changing industries, commission-based roles, founding an entity) for greater long-term growth.",
    subtitle: "Human capital risk appetite.",
    type: "likert-scale",
    dimension: "Calculated Risk Taking",
    options: [
      { id: "rsk_18_1", label: "Strongly Disagree", value: 1 },
      { id: "rsk_18_2", label: "Disagree", value: 2 },
      { id: "rsk_18_3", label: "Neutral", value: 3 },
      { id: "rsk_18_4", label: "Agree", value: 4 },
      { id: "rsk_18_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "rsk_q19",
    title: "I prefer safe investments with guaranteed low returns over investments that have a 30% chance of substantial gain and a 10% chance of moderate loss.",
    subtitle: "Reverse-scored expected value conservatism.",
    type: "likert-scale",
    dimension: "Calculated Risk Taking",
    reversed: true,
    options: [
      { id: "rsk_19_1", label: "Strongly Agree", value: 1 },
      { id: "rsk_19_2", label: "Agree", value: 2 },
      { id: "rsk_19_3", label: "Neutral", value: 3 },
      { id: "rsk_19_4", label: "Disagree", value: 4 },
      { id: "rsk_19_5", label: "Strongly Disagree", value: 5 },
    ],
  },
  {
    id: "rsk_q20",
    title: "Overall, how would you classify your personal financial risk appetite?",
    subtitle: "Self-perceived overall investor archetype.",
    type: "single-choice",
    dimension: "Calculated Risk Taking",
    options: [
      { id: "rsk_20_a", label: "Aggressive / Enterprising — I actively seek calculated upside and stomach heavy swings", value: 5 },
      { id: "rsk_20_b", label: "Moderate Growth — Balanced approach seeking equity returns with disciplined diversification", value: 4 },
      { id: "rsk_20_c", label: "Conservative — Preservation-oriented; drawdowns cause significant discomfort", value: 2 },
      { id: "rsk_20_d", label: "Ultra-Cautious — Capital preservation is paramount; zero tolerance for losses", value: 1 },
    ],
  },
];
