import { Question } from "@/types/question";

export const stressQuestions: Question[] = [
  // STAGE 1: Cognitive Pressure & Mental Pace (Questions 1–5)
  {
    id: "str_q1",
    title: "At the end of a typical day, how frequently do thoughts about unfinished obligations keep your mind racing?",
    subtitle: "Reflect on your ability to mentally disconnect from responsibilities.",
    type: "frequency",
    dimension: "Cognitive Pressure",
    reversed: true, // Frequent racing thoughts = lower resilience score
    options: [
      { id: "str_1_a", label: "Almost never — I easily compartmentalize", value: 1 },
      { id: "str_1_b", label: "Occasionally during high-demand weeks", value: 2 },
      { id: "str_1_c", label: "Frequently multiple nights per week", value: 3 },
      { id: "str_1_d", label: "Almost constantly every night", value: 4 },
    ],
  },
  {
    id: "str_q2",
    title: "I feel that the daily demands on my attention exceed my current bandwidth.",
    subtitle: "Rate how accurately this describes your experience over the past two weeks.",
    type: "likert-scale",
    dimension: "Cognitive Pressure",
    reversed: true,
    options: [
      { id: "str_2_1", label: "Strongly Disagree", value: 1 },
      { id: "str_2_2", label: "Disagree", value: 2 },
      { id: "str_2_3", label: "Neutral", value: 3 },
      { id: "str_2_4", label: "Agree", value: 4 },
      { id: "str_2_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "str_q3",
    title: "When multiple urgent requests arrive simultaneously, which describes your immediate internal state?",
    subtitle: "Situational response to sudden cognitive overload.",
    type: "scenario",
    dimension: "Cognitive Pressure",
    reversed: true,
    options: [
      { id: "str_3_a", label: "I calmly triage priorities and decline non-essential items.", value: 1, description: "Controlled proactive filtering" },
      { id: "str_3_b", label: "I feel brief tension, then systematically work through the queue.", value: 2, description: "Steady operational resilience" },
      { id: "str_3_c", label: "I rush frantically, attempting to address everything at once.", value: 3, description: "Scattered reactive acceleration" },
      { id: "str_3_d", label: "My thinking freezes and I experience sharp mental exhaustion.", value: 4, description: "Acute cognitive paralysis" },
    ],
  },
  {
    id: "str_q4",
    title: "I can easily sustain clear concentration without feeling mentally scattered or foggy.",
    subtitle: "Cognitive clarity under routine workload.",
    type: "likert-scale",
    dimension: "Cognitive Pressure",
    reversed: false, // Disagree = low, Agree = high resilience
    options: [
      { id: "str_4_1", label: "Strongly Disagree", value: 1 },
      { id: "str_4_2", label: "Disagree", value: 2 },
      { id: "str_4_3", label: "Neutral", value: 3 },
      { id: "str_4_4", label: "Agree", value: 4 },
      { id: "str_4_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "str_q5",
    title: "How often do you feel that you are running behind schedule regardless of your effort?",
    subtitle: "Subjective sense of perpetual time deficit.",
    type: "frequency",
    dimension: "Cognitive Pressure",
    reversed: true,
    options: [
      { id: "str_5_a", label: "Rarely or never", value: 1 },
      { id: "str_5_b", label: "Once or twice a month", value: 2 },
      { id: "str_5_c", label: "Several times weekly", value: 3 },
      { id: "str_5_d", label: "Daily or almost daily", value: 4 },
    ],
  },

  // STAGE 2: Physical Tension & Somatic Indicators (Questions 6–10)
  {
    id: "str_q6",
    title: "How frequently do you notice muscle tightness in your neck, shoulders, or jaw during the day?",
    subtitle: "Somatic manifestations of unconscious stress holding patterns.",
    type: "frequency",
    dimension: "Physical Tension",
    reversed: true,
    options: [
      { id: "str_6_a", label: "Rarely or never", value: 1 },
      { id: "str_6_b", label: "Occasionally when working long hours", value: 2 },
      { id: "str_6_c", label: "Most afternoons or evenings", value: 3 },
      { id: "str_6_d", label: "Constantly throughout every day", value: 4 },
    ],
  },
  {
    id: "str_q7",
    title: "My breathing remains deep, slow, and natural even when navigating challenging dilemmas.",
    subtitle: "Autonomic nervous system baseline regulation.",
    type: "likert-scale",
    dimension: "Physical Tension",
    reversed: false,
    options: [
      { id: "str_7_1", label: "Strongly Disagree", value: 1 },
      { id: "str_7_2", label: "Disagree", value: 2 },
      { id: "str_7_3", label: "Neutral", value: 3 },
      { id: "str_7_4", label: "Agree", value: 4 },
      { id: "str_7_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "str_q8",
    title: "When experiencing an unexpected delay or logistical inconvenience in public:",
    subtitle: "Select the physical reaction that most closely matches your body.",
    type: "scenario",
    dimension: "Physical Tension",
    reversed: true,
    options: [
      { id: "str_8_a", label: "My shoulders remain relaxed and my heart rate barely fluctuates.", value: 1, description: "Physiological calm" },
      { id: "str_8_b", label: "I feel a brief surge of impatience, then quickly settle back down.", value: 2, description: "Mild transient response" },
      { id: "str_8_c", label: "My jaw clenches, breathing shallows, and I pace restlessly.", value: 3, description: "Visceral stress mobilization" },
      { id: "str_8_d", label: "I experience intense stomach knots, chest tightness, or a headache.", value: 4, description: "Acute somatic distress" },
    ],
  },
  {
    id: "str_q9",
    title: "I experience tension headaches, eye strain, or sudden afternoon fatigue caused by stress.",
    subtitle: "Frequency of stress-induced physical symptoms.",
    type: "frequency",
    dimension: "Physical Tension",
    reversed: true,
    options: [
      { id: "str_9_a", label: "Never or very rarely", value: 1 },
      { id: "str_9_b", label: "Once or twice a month", value: 2 },
      { id: "str_9_c", label: "Weekly", value: 3 },
      { id: "str_9_d", label: "Multiple times per week", value: 4 },
    ],
  },
  {
    id: "str_q10",
    title: "I am able to physically release bodily tension on demand through stretching or relaxed breathing.",
    subtitle: "Somatic release self-efficacy.",
    type: "likert-scale",
    dimension: "Physical Tension",
    reversed: false,
    options: [
      { id: "str_10_1", label: "Strongly Disagree", value: 1 },
      { id: "str_10_2", label: "Disagree", value: 2 },
      { id: "str_10_3", label: "Neutral", value: 3 },
      { id: "str_10_4", label: "Agree", value: 4 },
      { id: "str_10_5", label: "Strongly Agree", value: 5 },
    ],
  },

  // STAGE 3: Emotional Load & Reactivity (Questions 11–15)
  {
    id: "str_q11",
    title: "How easily do minor everyday irritations (traffic, spills, slow internet) trigger sharp frustration?",
    subtitle: "Emotional threshold and reactivity buffer.",
    type: "frequency",
    dimension: "Emotional Load",
    reversed: true,
    options: [
      { id: "str_11_a", label: "Rarely — minor snags roll off my back", value: 1 },
      { id: "str_11_b", label: "Only when I am already tired or hungry", value: 2 },
      { id: "str_11_c", label: "Frequently — I feel on edge much of the day", value: 3 },
      { id: "str_11_d", label: "Almost always — small things feel overwhelmingly grating", value: 4 },
    ],
  },
  {
    id: "str_q12",
    title: "I have adequate emotional patience when interacting with family, colleagues, or strangers.",
    subtitle: "Interpersonal emotional reserve.",
    type: "likert-scale",
    dimension: "Emotional Load",
    reversed: false,
    options: [
      { id: "str_12_1", label: "Strongly Disagree", value: 1 },
      { id: "str_12_2", label: "Disagree", value: 2 },
      { id: "str_12_3", label: "Neutral", value: 3 },
      { id: "str_12_4", label: "Agree", value: 4 },
      { id: "str_12_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "str_q13",
    title: "When receiving unexpected constructive criticism on a project:",
    subtitle: "Emotional processing under evaluative vulnerability.",
    type: "scenario",
    dimension: "Emotional Load",
    reversed: true,
    options: [
      { id: "str_13_a", label: "I listen curiously and evaluate what can be constructively applied.", value: 1, description: "Grounded objective evaluation" },
      { id: "str_13_b", label: "I feel briefly defensive, but regain equilibrium within minutes.", value: 2, description: "Normal resilient adjustment" },
      { id: "str_13_c", label: "I dwell on the comments for days with lingering resentment.", value: 3, description: "Rumination and elevated sensitivity" },
      { id: "str_13_d", label: "I experience a severe dip in self-worth and motivation.", value: 4, description: "Emotional vulnerability depletion" },
    ],
  },
  {
    id: "str_q14",
    title: "I feel emotionally drained or exhausted before my workday even begins.",
    subtitle: "Anticipatory emotional burnout indicator.",
    type: "frequency",
    dimension: "Emotional Load",
    reversed: true,
    options: [
      { id: "str_14_a", label: "Never or rarely", value: 1 },
      { id: "str_14_b", label: "Occasionally", value: 2 },
      { id: "str_14_c", label: "Often (2–3 times a week)", value: 3 },
      { id: "str_14_d", label: "Almost every single morning", value: 4 },
    ],
  },
  {
    id: "str_q15",
    title: "I can laugh easily and maintain a sense of humor even during busy or chaotic weeks.",
    subtitle: "Psychological levity and emotional perspective.",
    type: "likert-scale",
    dimension: "Emotional Load",
    reversed: false,
    options: [
      { id: "str_15_1", label: "Strongly Disagree", value: 1 },
      { id: "str_15_2", label: "Disagree", value: 2 },
      { id: "str_15_3", label: "Neutral", value: 3 },
      { id: "str_15_4", label: "Agree", value: 4 },
      { id: "str_15_5", label: "Strongly Agree", value: 5 },
    ],
  },

  // STAGE 4: Recovery Margin & Restorative Practices (Questions 16–20)
  {
    id: "str_q16",
    title: "How many hours of genuine offline leisure (reading, walking, hobbies, rest) do you enjoy weekly?",
    subtitle: "Dedicated non-productive restorative margin.",
    type: "single-choice",
    dimension: "Recovery Margin",
    reversed: false, // More recovery hours = higher score
    options: [
      { id: "str_16_a", label: "Less than 2 hours", value: 1 },
      { id: "str_16_b", label: "3 to 5 hours", value: 2 },
      { id: "str_16_c", label: "6 to 10 hours", value: 4 },
      { id: "str_16_d", label: "10+ hours regularly", value: 5 },
    ],
  },
  {
    id: "str_q17",
    title: "I protect non-negotiable boundaries around my personal downtime and evening wind-down.",
    subtitle: "Boundary enforcement to prevent schedule creep.",
    type: "likert-scale",
    dimension: "Recovery Margin",
    reversed: false,
    options: [
      { id: "str_17_1", label: "Strongly Disagree", value: 1 },
      { id: "str_17_2", label: "Disagree", value: 2 },
      { id: "str_17_3", label: "Neutral", value: 3 },
      { id: "str_17_4", label: "Agree", value: 4 },
      { id: "str_17_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "str_q18",
    title: "When you finally take a day off or enter the weekend, what typically happens?",
    subtitle: "Post-work decompressive pattern.",
    type: "scenario",
    dimension: "Recovery Margin",
    reversed: false,
    options: [
      { id: "str_18_a", label: "I genuinely recharge, engage in enjoyable pursuits, and feel refreshed.", value: 5, description: "Restorative deep recovery" },
      { id: "str_18_b", label: "I take half a day to unwind, then settle into a relaxed rhythm.", value: 4, description: "Normal recovery cycle" },
      { id: "str_18_c", label: "I feel guilty for not working and spend hours checking messages.", value: 2, description: "Compulsive engagement failure" },
      { id: "str_18_d", label: "I collapse from exhaustion and feel just as depleted by Monday.", value: 1, description: "Chronic depletion deficit" },
    ],
  },
  {
    id: "str_q19",
    title: "I have reliable, restorative daily practices (e.g., breathwork, journaling, nature walks, quiet contemplation).",
    subtitle: "Active down-regulation toolkit.",
    type: "likert-scale",
    dimension: "Recovery Margin",
    reversed: false,
    options: [
      { id: "str_19_1", label: "Strongly Disagree", value: 1 },
      { id: "str_19_2", label: "Disagree", value: 2 },
      { id: "str_19_3", label: "Neutral", value: 3 },
      { id: "str_19_4", label: "Agree", value: 4 },
      { id: "str_19_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "str_q20",
    title: "Overall, how would you describe the balance between your daily energy output and daily energy renewal?",
    subtitle: "Macro energetic equilibrium over the past month.",
    type: "single-choice",
    dimension: "Recovery Margin",
    reversed: false,
    options: [
      { id: "str_20_a", label: "Heavy deficit — I am constantly burning reserves", value: 1 },
      { id: "str_20_b", label: "Slight deficit — I get through but feel steadily fatigued", value: 2 },
      { id: "str_20_c", label: "Balanced — output and rest are in healthy equilibrium", value: 4 },
      { id: "str_20_d", label: "Surplus — I feel vibrant, well-paced, and well-rested", value: 5 },
    ],
  },
];
