import { Question } from "@/types/question";

export const productivityQuestions: Question[] = [
  // STAGE 1: Goal Clarity & Prioritization (Questions 1–5)
  {
    id: "prd_q1",
    title: "Before beginning your workday, how clearly defined are your top 1–3 high-leverage outcomes?",
    subtitle: "Daily objective definition and cognitive clarity.",
    type: "single-choice",
    dimension: "Goal Clarity",
    options: [
      { id: "prd_1_a", label: "Crystal clear — written down in order of leverage before opening email", value: 5 },
      { id: "prd_1_b", label: "Generally clear in my head, though not always written down", value: 4 },
      { id: "prd_1_c", label: "Vague — I start working and figure out priorities as they appear", value: 2 },
      { id: "prd_1_d", label: "Completely reactive — I simply respond to incoming pings and messages", value: 1 },
    ],
  },
  {
    id: "prd_q2",
    title: "I can easily distinguish between high-leverage meaningful progress and low-value 'busywork'.",
    subtitle: "Value discrimination and leverage awareness.",
    type: "likert-scale",
    dimension: "Goal Clarity",
    options: [
      { id: "prd_2_1", label: "Strongly Disagree", value: 1 },
      { id: "prd_2_2", label: "Disagree", value: 2 },
      { id: "prd_2_3", label: "Neutral", value: 3 },
      { id: "prd_2_4", label: "Agree", value: 4 },
      { id: "prd_2_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "prd_q3",
    title: "Scenario: A colleague asks for help on an unexpected side project that conflicts with your primary weekly goal. What do you do?",
    subtitle: "Boundary enforcement around critical outcomes.",
    type: "scenario",
    dimension: "Goal Clarity",
    options: [
      { id: "prd_3_a", label: "I politely decline or negotiate a later date, protecting my core priority.", value: 5, description: "Disciplined boundary defense" },
      { id: "prd_3_b", label: "I spend 15 minutes pointing them to existing resources without derailing my schedule.", value: 4, description: "Helpful low-friction redirection" },
      { id: "prd_3_c", label: "I say yes immediately, causing my own project to fall behind schedule.", value: 2, description: "Pleasing compliance at cost of outcomes" },
      { id: "prd_3_d", label: "I take it on, get overwhelmed, and fail to deliver either project on time.", value: 1, description: "Chronic bandwidth collapse" },
    ],
  },
  {
    id: "prd_q4",
    title: "I regularly feel productive at the end of the day because my actual achievements aligned with my morning intent.",
    subtitle: "Execution-intent congruence.",
    type: "likert-scale",
    dimension: "Goal Clarity",
    options: [
      { id: "prd_4_1", label: "Strongly Disagree", value: 1 },
      { id: "prd_4_2", label: "Disagree", value: 2 },
      { id: "prd_4_3", label: "Neutral", value: 3 },
      { id: "prd_4_4", label: "Agree", value: 4 },
      { id: "prd_4_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "prd_q5",
    title: "How often do you find yourself working tirelessly all day without completing anything genuinely important?",
    subtitle: "Reverse-scored activity trap indicator.",
    type: "frequency",
    dimension: "Goal Clarity",
    reversed: true,
    options: [
      { id: "prd_5_a", label: "Rarely or never", value: 1 },
      { id: "prd_5_b", label: "Once or twice a month", value: 2 },
      { id: "prd_5_c", label: "Weekly", value: 3 },
      { id: "prd_5_d", label: "Almost every single day", value: 4 },
    ],
  },

  // STAGE 2: Distraction Control & Environment (Questions 6–10)
  {
    id: "prd_q6",
    title: "When working on a complex, intellectually taxing document, how often do you succumb to checking tabs or notifications?",
    subtitle: "Internal vs external distraction resistance.",
    type: "frequency",
    dimension: "Distraction Control",
    reversed: true,
    options: [
      { id: "prd_6_a", label: "Rarely — I stay locked in until a planned break", value: 1 },
      { id: "prd_6_b", label: "Every 30–45 minutes", value: 2 },
      { id: "prd_6_c", label: "Every 10–15 minutes whenever I hit mental friction", value: 3 },
      { id: "prd_6_d", label: "Constantly every few minutes", value: 4 },
    ],
  },
  {
    id: "prd_q7",
    title: "I have configured my workspace to minimize visual and auditory interruptions (e.g., closed door, noise cancellation, clean desk).",
    subtitle: "Environmental friction reduction.",
    type: "likert-scale",
    dimension: "Distraction Control",
    options: [
      { id: "prd_7_1", label: "Strongly Disagree", value: 1 },
      { id: "prd_7_2", label: "Disagree", value: 2 },
      { id: "prd_7_3", label: "Neutral", value: 3 },
      { id: "prd_7_4", label: "Agree", value: 4 },
      { id: "prd_7_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "prd_q8",
    title: "Scenario: You hit a difficult roadblock in your work and your brain signals an immediate craving for distraction. What happens?",
    subtitle: "Mental friction tolerance threshold.",
    type: "scenario",
    dimension: "Distraction Control",
    options: [
      { id: "prd_8_a", label: "I sit with the discomfort, sketch on scrap paper, and push through the barrier.", value: 5, description: "High friction tolerance" },
      { id: "prd_8_b", label: "I take a structured 3-minute physical break (water, stretch) and return to the problem.", value: 4, description: "Constructive somatic pause" },
      { id: "prd_8_c", label: "I reflexively open social media, news, or email for 'just five minutes'.", value: 2, description: "Avoidant dopamine escape" },
      { id: "prd_8_d", label: "I abandon the task entirely and move to easy, trivial busywork.", value: 1, description: "Productive procrastination surrender" },
    ],
  },
  {
    id: "prd_q9",
    title: "I can comfortably batch my communication (checking email and Slack at set windows) rather than living in an open inbox.",
    subtitle: "Asynchronous communication discipline.",
    type: "likert-scale",
    dimension: "Distraction Control",
    options: [
      { id: "prd_9_1", label: "Strongly Disagree", value: 1 },
      { id: "prd_9_2", label: "Disagree", value: 2 },
      { id: "prd_9_3", label: "Neutral", value: 3 },
      { id: "prd_9_4", label: "Agree", value: 4 },
      { id: "prd_9_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "prd_q10",
    title: "My concentration is easily shattered by background chatter or unexpected digital pings.",
    subtitle: "Reverse-scored sensory distractibility.",
    type: "likert-scale",
    dimension: "Distraction Control",
    reversed: true,
    options: [
      { id: "prd_10_1", label: "Strongly Agree", value: 1 },
      { id: "prd_10_2", label: "Agree", value: 2 },
      { id: "prd_10_3", label: "Neutral", value: 3 },
      { id: "prd_10_4", label: "Disagree", value: 4 },
      { id: "prd_10_5", label: "Strongly Disagree", value: 5 },
    ],
  },

  // STAGE 3: Execution Stamina & Deep Work (Questions 11–15)
  {
    id: "prd_q11",
    title: "On average, how many hours of deep, unbroken cognitive work do you achieve each day?",
    subtitle: "Cal Newport deep work capacity benchmark.",
    type: "single-choice",
    dimension: "Execution Stamina",
    options: [
      { id: "prd_11_a", label: "3 to 4+ hours of genuine deep focus", value: 5 },
      { id: "prd_11_b", label: "2 to 3 hours consistently", value: 4 },
      { id: "prd_11_c", label: "1 hour or scattered 20-minute bursts", value: 2 },
      { id: "prd_11_d", label: "Under 30 minutes; my day is entirely fragmented", value: 1 },
    ],
  },
  {
    id: "prd_q12",
    title: "I have the stamina to see projects through to complete finishing polish, not just 85% completion.",
    subtitle: "Closure stamina and shipping discipline.",
    type: "likert-scale",
    dimension: "Execution Stamina",
    options: [
      { id: "prd_12_1", label: "Strongly Disagree", value: 1 },
      { id: "prd_12_2", label: "Disagree", value: 2 },
      { id: "prd_12_3", label: "Neutral", value: 3 },
      { id: "prd_12_4", label: "Agree", value: 4 },
      { id: "prd_12_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "prd_q13",
    title: "When tackling a boring or repetitive requirement that is necessary for project success:",
    subtitle: "Affective persistence through administrative monotony.",
    type: "scenario",
    dimension: "Execution Stamina",
    options: [
      { id: "prd_13_a", label: "I time-block it, execute without drama, and celebrate the completed milestone.", value: 5, description: "Pragmatic execution efficiency" },
      { id: "prd_13_b", label: "I pair it with upbeat music or a coffee and knock it out steadily.", value: 4, description: "Positive environmental pacing" },
      { id: "prd_13_c", label: "I procrastinate for days until stress forces me to rush through it.", value: 2, description: "Avoidant deadline friction" },
      { id: "prd_13_d", label: "I ignore it entirely and hope someone else handles it.", value: 1, description: "Executive dereliction" },
    ],
  },
  {
    id: "prd_q14",
    title: "I can re-enter focus quickly after an unavoidable interruption.",
    subtitle: "Attention residue recovery speed.",
    type: "likert-scale",
    dimension: "Execution Stamina",
    options: [
      { id: "prd_14_1", label: "Strongly Disagree", value: 1 },
      { id: "prd_14_2", label: "Disagree", value: 2 },
      { id: "prd_14_3", label: "Neutral", value: 3 },
      { id: "prd_14_4", label: "Agree", value: 4 },
      { id: "prd_14_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "prd_q15",
    title: "I frequently start new projects with intense enthusiasm but lose steam before finishing.",
    subtitle: "Reverse-scored project completion endurance.",
    type: "likert-scale",
    dimension: "Execution Stamina",
    reversed: true,
    options: [
      { id: "prd_15_1", label: "Strongly Agree", value: 1 },
      { id: "prd_15_2", label: "Agree", value: 2 },
      { id: "prd_15_3", label: "Neutral", value: 3 },
      { id: "prd_15_4", label: "Disagree", value: 4 },
      { id: "prd_15_5", label: "Strongly Disagree", value: 5 },
    ],
  },

  // STAGE 4: System Consistency & Habit Infrastructure (Questions 16–20)
  {
    id: "prd_q16",
    title: "How consistently do you conduct a weekly review to plan upcoming milestones and clear task backlogs?",
    subtitle: "Systemic operating cadence.",
    type: "single-choice",
    dimension: "System Consistency",
    options: [
      { id: "prd_16_a", label: "Every week without fail (non-negotiable ritual)", value: 5 },
      { id: "prd_16_b", label: "2 to 3 times per month", value: 4 },
      { id: "prd_16_c", label: "Occasionally when chaos gets overwhelming", value: 2 },
      { id: "prd_16_d", label: "Never — I do not use a planning system", value: 1 },
    ],
  },
  {
    id: "prd_q17",
    title: "I have a trusted external system (calendar, task manager, notes) so I never rely purely on mental memory.",
    subtitle: "GTD cognitive offloading principle.",
    type: "likert-scale",
    dimension: "System Consistency",
    options: [
      { id: "prd_17_1", label: "Strongly Disagree", value: 1 },
      { id: "prd_17_2", label: "Disagree", value: 2 },
      { id: "prd_17_3", label: "Neutral", value: 3 },
      { id: "prd_17_4", label: "Agree", value: 4 },
      { id: "prd_17_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "prd_q18",
    title: "Scenario: Your productivity system becomes clogged with 80 overdue tasks and chaotic notes. What do you do?",
    subtitle: "System hygiene and reset resilience.",
    type: "scenario",
    dimension: "System Consistency",
    options: [
      { id: "prd_18_a", label: "I conduct a ruthless pruning session: archive stale items, keep top 10, and reset.", value: 5, description: "Decisive triage reset" },
      { id: "prd_18_b", label: "I systematically reschedule and prune over a couple of days.", value: 4, description: "Structured gradual cleanup" },
      { id: "prd_18_c", label: "I feel demoralized and abandon the system, switching to another shiny app.", value: 2, description: "Tool-hopping cycle" },
      { id: "prd_18_d", label: "I let it rot forever while feeling guilty every time I glance at it.", value: 1, description: "System paralysis" },
    ],
  },
  {
    id: "prd_q19",
    title: "I use standard operating templates or checklists for recurring workflows to save decision fatigue.",
    subtitle: "Procedural automation and cognitive conservation.",
    type: "likert-scale",
    dimension: "System Consistency",
    options: [
      { id: "prd_19_1", label: "Strongly Disagree", value: 1 },
      { id: "prd_19_2", label: "Disagree", value: 2 },
      { id: "prd_19_3", label: "Neutral", value: 3 },
      { id: "prd_19_4", label: "Agree", value: 4 },
      { id: "prd_19_5", label: "Strongly Agree", value: 5 },
    ],
  },
  {
    id: "prd_q20",
    title: "Overall, my productivity relies on reliable systems and environmental design rather than volatile willpower.",
    subtitle: "James Clear Atomic Habits principle.",
    type: "likert-scale",
    dimension: "System Consistency",
    options: [
      { id: "prd_20_1", label: "Strongly Disagree", value: 1 },
      { id: "prd_20_2", label: "Disagree", value: 2 },
      { id: "prd_20_3", label: "Neutral", value: 3 },
      { id: "prd_20_4", label: "Agree", value: 4 },
      { id: "prd_20_5", label: "Strongly Agree", value: 5 },
    ],
  },
];
